### ISSUE TITLE
vocabulary.txt和mean_std.npz文件

### ISSUE THREAD

**Issue by ORainn** [yeyupiaoling/PPASR#10]
您好，我下载了您的预训练模型，想要导出进行预测，请问这两个文件要怎么得到呢？
`add_arg('dataset_vocab',    str,   'dataset/vocabulary.txt',   '数据字典的路径')
add_arg('mean_std_path',    str,   'dataset/mean_std.npz',     '数据集的均值和标准值的npy文件路径')`

**Comment by yeyupiaoling** [comment]
你下载那些模型不就有了吗？

**Comment by ORainn** [comment]
擦大哥，怪我怪我，我以为那个文件夹没有东西哈哈哈，非常感谢你能这么快回复我！！！！！
祝你工作顺利~~

**Comment by rx-ted** [comment]
mean_std.npz我找不到了，放在哪儿

**Comment by yeyupiaoling** [comment]
dataset目录下，你执行create_list.py 或者 下载预训练模型都有的。

**Comment by rx-ted** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
