### ISSUE TITLE
推理问题

### ISSUE THREAD

**Issue by qinwangmm** [yeyupiaoling/PPASR#101]
大佬，下载了您那个大数据训练的模型，执行python infer_path.py --wav_path=./dataset/test.wav，
用了32G的GPU，预测时间是你的4倍，预测得分竟然是负数呢，我没有改代码，请问这是什么问题呢？

======================================================================
消耗时间：433ms, 识别结果: 近几年不但我用书给女儿压岁也劝说亲朋不要给女儿压岁钱而改送压岁书, 得分: -3

**Comment by yeyupiaoling** [comment]
估计你用的是集束搜索解码，这个是有负数的。贪心解码才是使用得分高的。

至于时间，你多预测几遍看看，可能是预热不够，你在同一个程序里面执行多次。你的是什么显卡？

**Comment by qinwangmm** [comment]
显卡是V100，换成贪心解码，确实速度和得分都变了。
消耗时间：66ms, 识别结果: 近几年不但我用输给女儿压岁也劝说亲朋不要给女儿压岁钱而改送压岁书, 得分: 97


评估的时候不是说集束搜索解码效果更好吗？那预测的时候不是用这个集束搜索解码吗？有点晕了








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/PPASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/PPASR] 推理问题 (Issue #101)





 
估计你用的是集束搜索解码，这个是有负数的。贪心解码才是使用得分高的。
 
至于时间，你多预测几遍看看，可能是预热不够，你在同一个程序里面执行多次。你的是什么显卡？

**Comment by yeyupiaoling** [comment]
解码使用的是CPU进行计算的，如果你的解码速度太慢的话，应该是以CPU的计算能力不够强。

**Comment by yeyupiaoling** [comment]
贪心解码器是计算每个字的最高得分。这样就会出现同音字的错误。集束搜索解码会判断结果是否合理。从而避免同音字错误。

**Comment by qinwangmm** [comment]
明白了，cpu都占用着呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/PPASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/PPASR] 推理问题 (Issue #101)





 解码使用的是CPU进行计算的，如果你的解码速度太慢的话，应该是以CPU的计算能力不够强。

**Comment by qinwangmm** [comment]
> 
好的，谢谢，我再看一下原理

**Comment by yeyupiaoling** [comment]
你的是什么cpu。

**Comment by yeyupiaoling** [comment]
哦哦，

**Comment by yeyupiaoling** [comment]
集束搜索解码准确率会更高。两种解码方式计算的方式不一样的，所以不能混为一谈。
