### ISSUE TITLE
在deepspeech2_big模型上继续训练

### ISSUE THREAD

**Issue by qinwangmm** [yeyupiaoling/PPASR#104]
大佬，我想在你的deepspeech2_big模型上继续训练，是不是缺少model.state和optimizer.pdopt这两个文件啊？

**Comment by yeyupiaoling** [comment]
作为预训练模型可以不需要这两个文件的。因为文件太大，我没上传。

**Comment by qinwangmm** [comment]
我看之前你在别人的问题回复中说的需要把model.state文件中的epoch改成1，需要使用你dataset目录下的两个文件

**Comment by qinwangmm** [comment]
还有一个问题，mean_std.npz这个文件必须是用你训练deepsepeech2_big模型时的文件对吧？不能用我目前新数据集生成的文件对吧？

**Comment by yeyupiaoling** [comment]
>model.state文件中的epoch改成1

这是一种做法，这种做法跟直接作为预训练模型差不多了。你的情况是怎样的？需要怎么训练？

dataset目录下的两个文件是有的吧。

**Comment by yeyupiaoling** [comment]
>能用我目前新数据集生成的文件对吧？

不能自己生成的。因为这个模型就是基于这种情况训练的，你换了就没用了

**Comment by qinwangmm** [comment]
我现在在处理wenet中的部分数据集，我需要把文件中不包含在你的vocabulary.txt文件中的字符相关的整条数据删掉吧？这样才能用你的vocabulary.txt继续训练吧，处理完我想训练看看，大佬预估一下，训练结果会好不好？

**Comment by yeyupiaoling** [comment]
如果修改vocabulary.txt，加载预训练模型的效果会大打折扣。
vocabulary.txt已经包含了很多字符，还有不存在的字符吗？
这个vocabulary.txt好像没有`<unk>`，这是最近才添加了，如果是有了`<unk>`，不存在的字符都会当作`<unk>`。

**Comment by qinwangmm** [comment]
不修改vocabulary.txt，把wenet中不在这个字典里的数据删掉

**Comment by qinwangmm** [comment]
这个vocabulary.txt好像没有<unk>，我把不存在的删掉

**Comment by yeyupiaoling** [comment]
要不你重新构建vocabulary.txt重新训练吧，我这数据集对应wenetspeech这个1W小时的数据集来说，不值一提。

**Comment by qinwangmm** [comment]
这个wenet训练起来太慢了，epoch1的cer:0.664，epoch2：0.5758，epoch3:0.5754 ,我都试一下看看哪个效果好

**Comment by yeyupiaoling** [comment]
嗯，你可以试试，应该不存在的字符也不会很多。

**Comment by qinwangmm** [comment]
嗯呢，字符十几个，不常见，繁体，我都不认识

**Comment by yeyupiaoling** [comment]
哈哈

**Comment by qinwangmm** [comment]
大佬。我追加训练，应该如下这样设置参数吧？
add_arg('batch_size',       int,    32,                       '训练的批量大小')
add_arg('num_workers',      int,    8,                        '读取数据的线程数量')
add_arg('num_epoch',        int,    65,                       '训练的轮数')
add_arg('learning_rate',    float,  5e-5,                     '初始学习率的大小')
add_arg('min_duration',     float,  0.5,                      '过滤最短的音频长度')
add_arg('max_duration',     int,    20,                       '过滤最长的音频长度，当为-1的时候不限制长度')
add_arg('use_model',        str,    'deepspeech2',              '所使用的模型', choices=['deepspeech2', 'deepspeech2_big'])
add_arg('train_manifest',   str,    'dataset/manifest.train',   '训练数据的数据列表路径')
add_arg('test_manifest',    str,    'dataset/manifest.test',    '测试数据的数据列表路径')
add_arg('dataset_vocab',    str,    'dataset/vocabulary.txt',   '数据字典的路径')
add_arg('mean_std_path',    str,    'dataset/mean_std.npz',     '数据集的均值和标准值的npy文件路径')
add_arg('augment_conf_path',str,    'conf/augmentation.json',   '数据增强的配置文件，为json格式')
add_arg('save_model_path',  str,    'models/',                  '模型保存的路径')
add_arg('feature_method',   str,    'linear',                   '音频预处理方法', choices=['linear', 'mfcc', 'fbank'])
add_arg('metrics_type',     str,    'cer',                      '计算错误率方法', choices=['cer', 'wer'])
add_arg('resume_model',     str,    None,                       '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str,    "models/deepspeech2_big/best_model",                       '预训练模型的路径，当为None则不
使用预训练模型')

**Comment by qinwangmm** [comment]
add_arg('resume_model', str, None, '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str, "models/deepspeech2_big/best_model", '预训练模型的路径，当为None则不
使用预训练模型')
这两个参数，我有点不明白了，我如果设置resume_model这个参数，跑不起来，需要你那个未上传的大文件

**Comment by yeyupiaoling** [comment]
应该这样：
```
add_arg('use_model', str, 'deepspeech2_big', '所使用的模型', choices=['deepspeech2', 'deepspeech2_big'])
```

**Comment by qinwangmm** [comment]
嗯，忘改了。
add_arg('resume_model', str, None, '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str, "models/deepspeech2_big/best_model", '预训练模型的路径，当为None则不
使用预训练模型')
这两个参数怎么改呢？

**Comment by yeyupiaoling** [comment]
就是这样

**Comment by qinwangmm** [comment]
好的，谢谢

**Comment by PING-An32** [comment]
大佬，我也想在您的conformer上面继续训练，我说一下我的步骤您看看有没有问题。
把自己的数据集添加进去之后，resume_model后面参数为None，pretrained_model参数为models/conformer_online_fbank/best_model，然后train若干个epoch。
得到了我自己本地的模型（有model.state和optimizer.pdopt）之后，以后训练pretrained_model就不再需要参数了，只需要把resume_model后的参数指定为我最后一次训练得到的就可以？

**Comment by yeyupiaoling** [comment]
做法完全正确

**Comment by PING-An32** [comment]
谢谢！ 我还比较好奇model.state和optimizer.pdopt的作用。比如我在指定您的模型为pretrained_model的时候，我大概需要train多少个epoch能完全继承下您模型的特征（因为没有model.state和optimizer.pdopt）。  还是说train的轮数没有影响？

**Comment by yeyupiaoling** [comment]
model.state只是记录了简单的训练状态，例如当前是第几个epoch，字错率是多少等
optimizer.pdopt是优化方法的参数，

微调的时候可以只使用模型参数就好，

**Comment by PING-An32** [comment]
明白了，感谢大佬解答！
