### ISSUE TITLE
大佬使用deepspeech2_big预测只要改图中这里就行吗，报了这个错

### ISSUE THREAD

**Issue by ZengLei-dev** [yeyupiaoling/PPASR#106]
![1660497502(1)](https://user-images.githubusercontent.com/53669083/184547873-f4d4b803-c633-4751-9271-75c71cf8f802.png)

![1660497592(1)](https://user-images.githubusercontent.com/53669083/184547911-cfbd3e0f-818a-4461-ba49-699a59234d14.png)
![1660497603(1)](https://user-images.githubusercontent.com/53669083/184547915-847de577-5eb1-434c-94fc-919edb8da772.png)

**Comment by yeyupiaoling** [comment]
![image](https://user-images.githubusercontent.com/26297768/184561186-54c48b30-1039-418e-b07a-ead843b3433f.png)

**Comment by yeyupiaoling** [comment]
这样路径也要指定

**Comment by ZengLei-dev** [comment]
大佬，都改了还是执行不了诶，模型下的目录结构也是deepspeech2_big的
![image](https://user-images.githubusercontent.com/53669083/184577464-dc224823-013b-43c0-b4cd-5953e5abbc08.png)
![1660538076(1)](https://user-images.githubusercontent.com/53669083/184577515-5dbcf031-45aa-4d8f-b206-23762706833f.png)
看这报错是不是得改模型代码呢

**Comment by ZengLei-dev** [comment]
debug调试时发现到self.predictor.run()就崩溃了
![1660538331(1)](https://user-images.githubusercontent.com/53669083/184577820-fbc5bc6b-9980-42fc-90a6-0cbe4e1e0db3.png)

**Comment by yeyupiaoling** [comment]
你看看你下载的和你指定的模型是否一致

**Comment by ZengLei-dev** [comment]
是一致的，我把参数改成deepspeech2，用这个就能预测
![1660544132(1)](https://user-images.githubusercontent.com/53669083/184585653-d03eecfa-36ae-4834-a289-fadf3811927b.png)

**Comment by yeyupiaoling** [comment]
你用的是最新代码吗？下载的那几个模型？

**Comment by ZengLei-dev** [comment]
是的最新的，用过thchs30,aishell,librispeech测过都可以，只是这个大数据集的不行

**Comment by yeyupiaoling** [comment]
你看看你的代码有没有这个
https://github.com/yeyupiaoling/PPASR/blob/7e756d8f5a7eca7cbeebc5673c033625add8261f/ppasr/predict.py#L72-L75

**Comment by ZengLei-dev** [comment]
我去，确实没有，感谢大佬

**Comment by yeyupiaoling** [comment]
那就是旧代码，

**Comment by ZengLei-dev** [comment]
明白了，看来我记错了，请问用这个大数据模型预测自己录的音频效果怎么样呢

**Comment by yeyupiaoling** [comment]
这些准确率都是基于现有的数据集的，识别效果还得自己测试。
要使用集束搜索解码器。

**Comment by ZengLei-dev** [comment]
好的，谢谢您了
