### ISSUE TITLE
如何在预训练模型的基础上用自己的数据集进行fine-tune

### ISSUE THREAD

**Issue by zbh201** [yeyupiaoling/PPASR#111]
大佬，我想问下这个框架提供在预训练模型上进行fine-tune的接口吗？按照数据准备文档里的描述对自己的数据集进行操作后要怎么进行操作呢？

**Comment by yeyupiaoling** [comment]
在这里指定我的模型，训练轮数加上10试试看

https://github.com/yeyupiaoling/PPASR/blob/4ab67afce594e6af898564c1a6da6e0ead2b85c9/train.py#L14

**Comment by zbh201** [comment]
想问下大佬后续会增加conformer模型吗

**Comment by zbh201** [comment]
想问下大佬后续会增加conformer模型吗

**Comment by yeyupiaoling** [comment]
@zbh201 新版本已发布，支持conformer了
