### ISSUE TITLE
关于8k采样率训练参数问题

### ISSUE THREAD

**Issue by Tian14267** [yeyupiaoling/PPASR#112]
大神你好，请问下，当前的训练参数是基于`16k`采样率的（中文）。我现在想训练`8k`采样率的模型。请问下能否公布一份基于`8K`采样率的训练参数配置？因为我自己修改的参数不确定是否有问题。拜托大神了。

**Comment by yeyupiaoling** [comment]
看这个参数
https://github.com/yeyupiaoling/PPASR/blob/e4883a9c290bbb86ebb7910256b23bf9ddfd14b5/configs/config_zh.yml#L31

**Comment by Tian14267** [comment]
> 看这个参数
> 
> https://github.com/yeyupiaoling/PPASR/blob/e4883a9c290bbb86ebb7910256b23bf9ddfd14b5/configs/config_zh.yml#L31

好的大神。我想问的是，想要修改8k的采样率，除了修改采样率参数，其他参数要一并修改嘛。比如n_mels ，n_mfcc，等等。我听别人说，16k降到8k,  n_mels等参数也要减半，是这样嘛

**Comment by yeyupiaoling** [comment]
这个你试试就知道了。
