### ISSUE TITLE
训练一个epoch就自动退出了，是什么原因呢

### ISSUE THREAD

**Issue by leilei97** [yeyupiaoling/PPASR#114]
本地配置进阶版，训练自己的数据集，训练一个epoch就自动退出了，是什么原因呢
运行时gpu没有占满用了5/6大概，我调小参数还是一个epoch就自动退出
大佬帮忙看看是什么原因导致的
![image](https://user-images.githubusercontent.com/59796626/199194227-e4aae766-89eb-4232-b385-b4d5891ca967.png)

**Comment by yeyupiaoling** [comment]
没有任何提示？你减小batch size试试看

**Comment by leilei97** [comment]
![image](https://user-images.githubusercontent.com/59796626/199202926-0b1d3bf1-5b54-461c-8b61-14e670cf1f90.png)
大佬您看，还是一样，我调成4了，gpu就用了一半

**Comment by yeyupiaoling** [comment]
这个我也看不出是什么问题了。要不你换成Linux系统或者使用最新代码试一下。

**Comment by leilei97** [comment]
好的，谢谢
