### ISSUE TITLE
训练一个epoch之后停下了

### ISSUE THREAD

**Issue by Tian14267** [yeyupiaoling/PPASR#119]
你好大神，我遇到一个问题，就是训练一个epoch之后，代码自动停了。然后GPU还在占用着。没有发现报错。具体如下图：
<img width="706" alt="a69e999e48c3c1436b85e843e10df94" src="https://user-images.githubusercontent.com/27938135/201565779-7b3c8274-daa1-4062-9457-f1bbe9708b9b.png">

请问下这个是啥原因啊

**Comment by yeyupiaoling** [comment]
你设置的训练轮数多少？直接停的吗？

**Comment by Tian14267** [comment]
我初步发现这个问题。我再重跑一下看看

**Comment by Tian14267** [comment]
> 你设置的训练轮数多少？直接停的吗？

设置的是100轮。我准备把log截图出来的，但是刚刚重跑了一下，log好像推掉了。我跑了两台机子，都出现这个问题了

**Comment by yeyupiaoling** [comment]
多卡训练还是单卡训练？

**Comment by yeyupiaoling** [comment]
会不会是你加载的预训练模型本身就训练就够了。

**Comment by Tian14267** [comment]
> 你设置的训练轮数多少？直接停的吗？

准确的说，是第一个epoch刚跑完就结束了。我是重头开始训练的，第一个epoch结束之后就不动了。我看看能不能把详情上传上来

**Comment by Tian14267** [comment]
[nohup_train_5.zip](https://github.com/yeyupiaoling/PPASR/files/9999226/nohup_train_5.zip)

**Comment by Tian14267** [comment]
> 会不会是你加载的预训练模型本身就训练就够了。

我把详情上传上来了。最后一行 kill 是我早上来手动kill的

**Comment by yeyupiaoling** [comment]
应该是某个卡出现问题导致全部都是死掉的，这个要看log里面的日志。

**Comment by yeyupiaoling** [comment]
你可以看加群吗？这样聊得快一点。
