### ISSUE TITLE
多卡训练时爆显存的问题

### ISSUE THREAD

**Issue by upc-hao** [yeyupiaoling/PPASR#120]
单块tesla-T4 16G设置batchsize为8可以正常跑完训练，多卡训练选择两块T4，batchsize设置16个就爆显存了，而且爆显存重启内核后nvidia-smi查看，0号显存正常释放了，1号显存一直是接近百分百占用率。从下午到晚上也没整明白原因，求教大神多卡训练还需要额外的设置吗？
![image](https://user-images.githubusercontent.com/9252754/202856235-bd63cfda-6ba6-4fc3-9f68-e256891a17a4.png)

**Comment by yeyupiaoling** [comment]
>多卡训练选择两块T4，batchsize设置16个就爆显存了

多卡还是8才对啊，你只是卡多了，有不是显存多了
