### ISSUE TITLE
self.cached_feat = np.concatenate([self.cached_feat, x_chunk], axis=1)  这里是写反了吗，x_chunk是不是应该在cached_feat前面

### ISSUE THREAD

**Issue by sususushi** [yeyupiaoling/PPASR#121]
https://github.com/yeyupiaoling/PPASR/blob/418f2790fbf118d87f02e43cca4c11dba9e47c10/ppasr/predict.py#L230

self.cached_feat = np.concatenate([self.cached_feat, x_chunk], axis=1)  这里是写反了吗，x_chunk是不是应该在cached_feat前面

**Comment by yeyupiaoling** [comment]
你要不自己试试
