### ISSUE TITLE
博主有没有办法解决多线程的问题?

### ISSUE THREAD

**Issue by wxy0505** [yeyupiaoling/PPASR#126]
我batch_size设置16,线程设置0可以训练，但我线程设置4或者2时，batch_size设置8或者4时都会卡住不动。

**Comment by wxy0505** [comment]
而且在卡住的时候我看GPU的利用率是0

**Comment by yeyupiaoling** [comment]
应该随机的吧，我一般减小batch_size就可以了。或你设置为2
https://github.com/yeyupiaoling/PPASR/blob/855b72ef02c5b03ae365e117687785e4950586de/configs/conformer_online_zh.yml#L42
