### ISSUE TITLE
请问预训练模型列表conformer_online(WenetSpeech10000小时)训练的轮数？与改变batch_size后是否要重新训练？

### ISSUE THREAD

**Issue by springminhcm** [yeyupiaoling/PPASR#127]
博主您好，请问一下，目前提供的预训练模型列表conformer_online(WenetSpeech10000小时)训练的轮数是多少次呢？

另外关于batch_size的部份，若一开始我设为32，然后训练5轮时，因出现gpu ram不足的讯息，此时我改batch_size为16后，是可以直接从第5轮挂载后重新训练即可？还是要从第一轮重新训练呢？

**Comment by yeyupiaoling** [comment]
不需要的，直接执行训练，会自动加载last_model

**Comment by springminhcm** [comment]
谢谢博主的回覆。不知可否方便吿知一下预训练模型列表conformer_online(WenetSpeech10000小时)训练的轮数是多少次？我只是单纯的了解一下，想达到目前conformer_online WenetSpeech的效果，大概要训练多少次这样？因为那10000小时我也有下载，训练一次(gpu 3090)真的要蛮久的时间@@

**Comment by yeyupiaoling** [comment]
100-200之间，中间看到多次没有提升之后，就可以停止训练了。

**Comment by springminhcm** [comment]
哇100次以上？太惊人了....(我只有单卡3090)谢谢博主的回覆。我还是使用小一点的模型好了^^||
