### ISSUE TITLE
改变batch_size后，num_workers和learning_rate要随之改变吗

### ISSUE THREAD

**Issue by Skeleton003** [yeyupiaoling/PPASR#128]
因为电脑太旧了，我把batch_size改成了4（因为8以上就跑不了了），请问num_workers和learning_rate应该相应地改为多少？

另外，我在batch_size=4，num_workers=4，learning_rate=1e-3的设置下跑了十几个epoch，cer就一直是1.0了，这正常吗？

**Comment by yeyupiaoling** [comment]
学习率可以按倍数减少。你训练那个模型，是不是用最新的代码分支develop

**Comment by Skeleton003** [comment]
> 学习率可以按倍数减少。你训练那个模型，是不是用最新的代码分支develop

我训练入门级

**Comment by yeyupiaoling** [comment]
胆子大点，直接使用最终级

**Comment by Skeleton003** [comment]
所以cer降不下来是因为入门级的模型有问题吗

**Comment by yeyupiaoling** [comment]
也不是，可能你学习率太大了，也有可能是随机初始化的问题。

**Comment by Skeleton003** [comment]
学习率调小后cer和loss果然降下来了，感谢。
