### ISSUE TITLE
No such file or directory: 'dataset/vocabulary.txt'?

### ISSUE THREAD

**Issue by yourengod** [yeyupiaoling/PPASR#131]
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/vocabulary.txt'

**Comment by yeyupiaoling** [comment]
你的版本不是最新的，要ppasr 2.2.1

**Comment by yourengod** [comment]
你好，我从github上下载的源程序，没有见到ppasr 2.2.1啊？

**Comment by yeyupiaoling** [comment]
你重新拉取，昨天更新的

**Comment by yourengod** [comment]
是直接使用正在开发的版本吗？

**Comment by yeyupiaoling** [comment]
嗯嗯

**Comment by yourengod** [comment]
![image](https://user-images.githubusercontent.com/6347733/210479206-26cb5517-c9a5-4b37-a1b1-1b2a57007714.png)
还是这个错误

**Comment by yeyupiaoling** [comment]
你不是用快速使用那个的话，你有没有下载模型和导出模型，还是说你直接训练？
我都没看到你的模型文件

**Comment by yourengod** [comment]
直接使用的。是要自己下载模型，放到根文件下吗？

**Comment by yeyupiaoling** [comment]
先自己认真看文档，尝试一下先。

**Comment by yourengod** [comment]
你好，请教一下，导出模型时报这个问题：
![image](https://user-images.githubusercontent.com/6347733/210486248-372fdd30-d276-4fb5-b26b-2dc4fbe6ad08.png)

**Comment by yourengod** [comment]
你好，请教一下，导出模型时报这个问题：下载的模型已经放到“infer”下面了，执行“python.exe export_model.py --resume_model=models/conformer_online_fbank/best_model/”。
![image](https://user-images.githubusercontent.com/6347733/210486417-692ded25-7e8d-483b-8fd7-db865a1a4dd2.png)

**Comment by yeyupiaoling** [comment]
你下载的模型文件全部解压到项目根目录，
你下载的是语言模型

**Comment by yourengod** [comment]
023-01-04 15:27:46 INFO   ] utils:print_arguments:33 - use_model: conformer_online
[2023-01-04 15:27:46 INFO   ] utils:print_arguments:34 - ------------------------------------------------
  File "E:\tmp\PPASR\ppasr\model_utils\conformer\model.py", line 212, in ConformerModelOnline
    model = ConformerModel(configs=configs,
  File "E:\tmp\PPASR\ppasr\model_utils\conformer\model.py", line 31, in __init__
    feature_normalizer = FeatureNormalizer(mean_istd_filepath=configs.dataset_conf.mean_istd_path)
  File "E:\tmp\PPASR\ppasr\data_utils\normalizer.py", line 31, in __init__
    self.mean, self.istd = self._read_mean_istd_from_file(mean_istd_filepath)
  File "E:\tmp\PPASR\ppasr\data_utils\normalizer.py", line 40, in _read_mean_istd_from_file
    istd = np.array(data["istd"], dtype=np.float32)
KeyError: 'istd'

**Comment by yourengod** [comment]
请问这是咋了？

**Comment by yourengod** [comment]
![image](https://user-images.githubusercontent.com/6347733/210514734-43f26745-41fa-4a74-a034-7583df4ec7ae.png)
请问，我如何把模型文件的路径指向当前项目而不是“  cache_dir = os.path.expanduser("~/.cache/ppasr")”这个目录？

**Comment by yourengod** [comment]
这个知道了：
请问，我如何把模型文件的路径指向当前项目而不是“ cache_dir = os.path.expanduser("~/.cache/ppasr")”这个目录？
