### ISSUE TITLE
OSError: (External) CUDA error(719)

### ISSUE THREAD

**Issue by new786786** [yeyupiaoling/PPASR#134]
开始训练的时候出错了

OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:259)
 好几次更换paddle版本  还是同样的错误

**Comment by yeyupiaoling** [comment]
这个应该是cuda版本的问题，你用conda安装PaddlePaddle，试试cuda 11.6那个版本
