### ISSUE TITLE
导不出aishell deepspeech2的模型

### ISSUE THREAD

**Issue by navy7913** [yeyupiaoling/PPASR#136]
您好，想您请教一个问题，我将模型下载下来后将原本的config、dataset取代掉，然后更改export_model.py里的路径要来导出模型，然后出现了错误，错误如图一，图二这是我的档案位置，不知道是否是我搞错放错地方了，图三是我的export_model.py的程式码。
![圖一](https://user-images.githubusercontent.com/119503098/216500275-1b1075f2-cd4c-475b-8b40-cedf66095239.JPG)
![圖二](https://user-images.githubusercontent.com/119503098/216500277-00fb8d61-5690-4c24-9913-caf110fd208f.JPG)
![圖三](https://user-images.githubusercontent.com/119503098/216500280-4fda93cb-f0af-4637-a5b0-9f7257428c6e.JPG)

**Comment by yeyupiaoling** [comment]
应该是你代码比较旧。你重新拉取一下代码。
