### ISSUE TITLE
流式识别几分钟之后报错

### ISSUE THREAD

**Issue by shnn98** [yeyupiaoling/PPASR#137]
您好，流式识别刚开始几分钟可以正常运行，大概四分钟之后有如下报错，请问这是什么原因？
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8, 16, 5008] and the shape of Y = [1, 8, 16, 5000]. Received [5008] in X is not equal to [5000] in Y at i:3.
[Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:84)
[operator < elementwise_add > error]

**Comment by yeyupiaoling** [comment]
这可能是数据分割的时候出现了问题。
你流式识别这么长时间了吗？
可以考虑移动时间之后停止重新开始

**Comment by shnn98** [comment]
我有时几分钟没关，然后出错的。我试一下你的方案
