### ISSUE TITLE
启动infer_server 流式识别报错

### ISSUE THREAD

**Issue by 2954456878** [yeyupiaoling/PPASR#139]
![image](https://user-images.githubusercontent.com/88914706/220810566-4808c3e8-db0e-45b9-9f27-6008a01b33bf.png)
![image](https://user-images.githubusercontent.com/88914706/220810600-045d52b4-999a-4c0f-8639-f9e7a635d2ce.png)

**Comment by yeyupiaoling** [comment]
应该是你没有使用正确的配置文件吧。因为要通过配置文件指定不同的模型

**Comment by 2954456878** [comment]
> 应该是你没有使用正确的配置文件吧。因为要通过配置文件指定不同的模型

![image](https://user-images.githubusercontent.com/88914706/220818968-d07fc180-e526-4a5e-8f25-9295b40349cd.png)
请问是这个配置文件吗 需要修改哪些地方呢

**Comment by yeyupiaoling** [comment]
我看你配置文件好像也是指定了deepspeech2，你这个预测模型也是deepspeech2模型吗？

**Comment by 2954456878** [comment]
> 我看你配置文件好像也是指定了deepspeech2，你这个预测模型也是deepspeech2模型吗？

是的 在网上找的一个deepspeech2 模型

**Comment by 2954456878** [comment]
> 我看你配置文件好像也是指定了deepspeech2，你这个预测模型也是deepspeech2模型吗？

![image](https://user-images.githubusercontent.com/88914706/220829509-3ed20839-5bc1-47e6-935f-161383724e1a.png)

**Comment by yeyupiaoling** [comment]
网上找的，你不是用我项目的模型吗？

**Comment by 2954456878** [comment]
> 网上找的，你不是用我项目的模型吗？

大佬 是否有百度云 ；我直接在网上下的预测模型

**Comment by 2954456878** [comment]
> 网上找的，你不是用我项目的模型吗？

大佬 是否有百度网盘，我是直接在csdn下的预测模型

**Comment by yeyupiaoling** [comment]
如果你不是用我项目提供的模型预测的话，是不能用的，你其他地方下载的怎么能在我这里使用呢？

**Comment by 2954456878** [comment]
> 如果你不是用我项目提供的模型预测的话，是不能用的，你其他地方下载的怎么能在我这里使用呢？

是大佬你在csdn提供的 "PPASR流式与非流式语音识别模型 " 这个模型

**Comment by yeyupiaoling** [comment]
是当前分支的吗？有没有正确导出模型的？

**Comment by 2954456878** [comment]
> 是当前分支的吗？有没有正确导出模型的？

是当前分支的，大佬在csdn提供的模型直接就是预测模型了吧？没有mean_istd.json这些文件的

**Comment by 2954456878** [comment]
> 是当前分支的吗？有没有正确导出模型的？

我用大佬项目主页百度网盘里面的 在试试

**Comment by 2954456878** [comment]
导出模型成功后，开始server 提示语音模型不存在 这个模型应该在哪里下载呢
![image](https://user-images.githubusercontent.com/88914706/220834679-7ae16eff-3c96-4204-a2cf-d3aadc86745e.png)

**Comment by 2954456878** [comment]
感谢大佬指点
