### ISSUE TITLE
请问是否有测试的client.py 通过websocket连接服务端 ，进行实时流式识别

### ISSUE THREAD

**Issue by 2954456878** [yeyupiaoling/PPASR#140]

**Comment by yeyupiaoling** [comment]
有这个程序吗？

**Comment by 2954456878** [comment]
infer_server启动服务器

**Comment by 2954456878** [comment]
infer_server启动服务端后，想有一个client.py通过websocket  ip和端口的方式，从其他客户端传输实时语音流到这边服务端进行识别并返回结果，现在项目有这个client.py吗

**Comment by 2954456878** [comment]
> 有这个程序吗？

infer_server启动服务端后，想有一个client.py通过websocket ip和端口的方式，从其他客户端传输实时语音流到这边服务端进行识别并返回结果，现在项目有这个client.py吗

**Comment by yeyupiaoling** [comment]
&nbsp;giu那个文件就包含了这个功能了。

**Comment by 2954456878** [comment]
是的 感谢大佬 已经通过参考该脚本实现了该功能
