### ISSUE TITLE
训练自己的语料时，执行create_data.py 报错

### ISSUE THREAD

**Issue by 2954456878** [yeyupiaoling/PPASR#141]
![image](https://user-images.githubusercontent.com/88914706/220867626-d8c59ef0-5970-4d51-89b7-c8113baad221.png)
数据存放在audio里面；标注存放在annotation下面

**Comment by yeyupiaoling** [comment]
看样子好像是数据分割失败哦。你用的是table键吗？

**Comment by 2954456878** [comment]
> 看样子好像是数据分割失败哦。你用的是table键吗？

是用的table建 分割的路径和语音文字
