### ISSUE TITLE
实时识别的时候，请问怎么让服务端返回的结果只返回我发送的16000字节的识别结果，而不是每次将上一次的结果拼接后一起返回

### ISSUE THREAD

**Issue by qqllh** [yeyupiaoling/PPASR#144]
如图
![image](https://user-images.githubusercontent.com/126734252/222303931-dd4c3960-1296-45ad-b7f0-dddc1d50bd61.png)
 我每次发送16000 bytes，只希望服务端识别这16000 bytes字节，并返回对应的结果，而不是将之前识别的结果拼接后一起返回。

**Comment by yeyupiaoling** [comment]
你可以改一下返回结构。
