### ISSUE TITLE
PPASR这个版本能转阿拉伯数字吗？

### ISSUE THREAD

**Issue by linlin6090** [yeyupiaoling/PPASR#146]

**Comment by yeyupiaoling** [comment]
可以的，如果用ctc_greedy解码器，可以使用itn文本反标准化处理，如果是用ctc_beam_search解码器，会自动切换为cn2an转换，但是这个效果一般。
这里开启：
https://github.com/yeyupiaoling/PPASR/blob/148824bee98c4b784400c9354b2c9f16869dd113/infer_path.py#L17
