### ISSUE TITLE
下载预训练模型后如何微调呢。

### ISSUE THREAD

**Issue by PANPANKK** [yeyupiaoling/PPASR#147]
使用预训练模型，然而在填路径时报错。不知道填的对不对？
add_arg('resume_model',     str,    './models/conformer_streaming_fbank/last_model/',                       '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str,    './models/conformer_streaming_fbank/best_model/', '预训练模型的路径，当为None则不使用预训练模型')
还有一个问题是，要想微调，其步骤是否为：下载预训练模型文件，导出模型，填写上述两个路径呢？希望博主能给予解答，谢谢谢谢~

**Comment by yeyupiaoling** [comment]
如果你用一训练模型就用这个:pretrained_model
如果你训练中断了，想恢复训练用这个:resume_model

**Comment by PANPANKK** [comment]
AssertionError: Variable Shape not match, Variable [ embedding_0.w_0_moment1_0 ] need tensor with shape [3894, 256] but load set tensor with shape [463, 256]。
按照你说的，我使用预训练模型，把resume_model设置为none. 但出现错误，是否是因为这里程序还是调用了我使用自己数据创建的字典、归一化文件等导致的呢~


蒋培元
***@***.***

18638063302


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/PPASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/PPASR] 下载预训练模型后如何微调呢。 (Issue #147)





 
如果你用一训练模型就用这个:pretrained_model
 如果你训练中断了，想恢复训练用这个:resume_model

**Comment by yeyupiaoling** [comment]
你的是不是有last_model文件夹

**Comment by PANPANKK** [comment]
是的，需要删除嘛
&nbsp;


蒋培元
***@***.***

18638063302


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/PPASR] 下载预训练模型后如何微调呢。 (Issue #147)





 
你的是不是有last_model文件夹

**Comment by yeyupiaoling** [comment]
要

**Comment by PANPANKK** [comment]
谢谢博主，删完已解决问题~
&nbsp;


蒋培元
***@***.***

18638063302


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/PPASR] 下载预训练模型后如何微调呢。 (Issue #147)





 
要
