### ISSUE TITLE
大佬，后续有没有增加热词功能的计划吗？

### ISSUE THREAD

**Issue by lwppwl** [yeyupiaoling/PPASR#148]
大佬，我看到有种说法，要识别一个特殊的词汇，我们不需要将含有这个词汇的音频加入到模型重新训练（前提有一个很好的预训练模型），而是通过热词的方式，就能很好的识别出来，这种说法是否正确呢？
市面上很多语音识别厂商支持热词，大佬有计划增加热词吗？

**Comment by yeyupiaoling** [comment]
是的，热词功能是语音识别很重要一部分。以后会增加这个功能的，但短期内没有排期
