### ISSUE TITLE
标点符号

### ISSUE THREAD

**Issue by dyfcode** [yeyupiaoling/PPASR#15]
想问下大佬，根据停顿添加标点符号怎么做？需要添加分词吗？

**Comment by yeyupiaoling** [comment]
我计划打算用VAD的方式。

**Comment by yeyupiaoling** [comment]
@dyfcode 
最新版本支持添加标点符号了：
https://github.com/yeyupiaoling/PPASR/blob/master/docs/punctuation.md

**Comment by dyfcode** [comment]
> @dyfcode 最新版本支持添加标点符号了： https://github.com/yeyupiaoling/PPASR/blob/master/docs/punctuation.md

大佬厉害，我最近也在加标点，但是效果不是很好，向你多学习！
