### ISSUE TITLE
语音活动检测可以检测英文吗

### ISSUE THREAD

**Issue by zhaoloulou** [yeyupiaoling/PPASR#150]
from ppasr.infer_utils.vad_predictor import VADPredictor
vad_predictor = VADPredictor()
wav, sr = soundfile.read('dataset/test.wav', dtype=np.float32)
speech_timestamps = vad_predictor.get_speech_timestamps(wav, sr)
输入不同的英文音频后，均报错ValueError: Input audio chunk is too short，输入中文音频没问题
是因为该模型不支持英文音频吗？

**Comment by yeyupiaoling** [comment]
跟语言没多太大关系的，应该就是音频太短了吧
