### ISSUE TITLE
模型预测问题

### ISSUE THREAD

**Issue by Xxzz1** [yeyupiaoling/PPASR#151]
请问一下为什么预测的结果是这样的，预测模型是从博主你主页下载的conformere那个
![image](https://user-images.githubusercontent.com/63334715/227417187-ec48849b-e159-4cf7-853d-dd5735b5e263.png)

**Comment by yeyupiaoling** [comment]
下载的模型，要全部复制到项目根目录里面，你应该是缺失了dataset里面的文件吧，或者是导出模型的是没有设置对路径
