### ISSUE TITLE
infer_server.py多进程预测问题

### ISSUE THREAD

**Issue by shop668** [yeyupiaoling/PPASR#152]
您好：
        看到您更新了infer_server.py的多进程预测，我进行了测试，发现问题如下，还请帮忙一下
问题1：无论参数--use_gpu=False还是=True，启动之后都会加载GPU内存
问题2：我使用python infer_server.py --num_web_p=2或者python infer_server.py 或者 python infer_server.py --use_gpu=False启动，进行不管是长语音转写还是短语音转写，都会报如下错误：

[2023-03-24 05:03:08.803234] 短语音识别失败，错误信息：(External) CUDA error(3), initialization error.
  [Hint: Please search for the error code(3) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:172)

![image](https://user-images.githubusercontent.com/48200794/227429077-d7582fc0-3db9-4330-92b3-ebdb29a012fd.png)

**Comment by yeyupiaoling** [comment]
应该是使用多进程的时候，不会再从命令里面获取参数输入，导致一直都是使用程序里面的默认参数
