### ISSUE TITLE
在linux上 使用本地预测遇到CUBLAS error(13)

### ISSUE THREAD

**Issue by navy7913** [yeyupiaoling/PPASR#156]
環境:
gpu 3060ti
 ubuntu 18.04
 Driver version 510
 cuda 11.8
 cudnn 8.4
 下载的环境是paddlepaddle-gpu==2.4.1 cudatoolkit=11.2

在linux上使用infer_path出现CUBLAS error(13)的错误，想请教如何解决这个问题，错误提示请参考下图
![image](https://user-images.githubusercontent.com/119503098/235304438-2fa85e7f-e1ef-412f-93c6-9e21efa3e6a6.png)

**Comment by yeyupiaoling** [comment]
你检查过你的环境能正常运行起来吗？有在这个环境跑过其他的项目吗？我觉得可能是cudnn和cuda问题

**Comment by navy7913** [comment]
> 你检查过你的环境能正常运行起来吗？有在这个环境跑过其他的项目吗？我觉得可能是cudnn和cuda问题

目前只知道可以成功运行export_model，如果是cuda和cudnn出问题是因为版本的关系吗?

**Comment by navy7913** [comment]
您好我有重新安装新的cuda和cudnn环境(参考图一)，安装完成后错误提示变成图二所示，想请教您会出现这个错误是因为版本和paddlepaddle-gpu不匹配所导致的吗?

環境:
gpu 3060ti
ubuntu 18.04
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.7

![image](https://user-images.githubusercontent.com/119503098/235340920-b397e5d7-daa9-430d-99bc-ebc8306f8434.png)
图一

![image](https://user-images.githubusercontent.com/119503098/235340941-061d41d2-6df9-4538-9e3a-d3d613d869ab.png)
图二

RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcufft.so) that Paddle depends on is not configured correctly. (error code is libcufft.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:305)

**Comment by navy7913** [comment]
您好，我将paddlepaddle-gpu换成这个版本就可以成功运行了
conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
