### ISSUE TITLE
求助，gui引入三个标点的模型后无法打开文件选择器

### ISSUE THREAD

**Issue by tianyadiaoxianbing** [yeyupiaoling/PPASR#157]
![image](https://user-images.githubusercontent.com/86992319/236249156-d432f3e1-2665-4c98-8391-90426f4e04a8.png)
求助，把use_pun设成False,不使用加标点的模型可以使用，不使用infer_path可以使用这个加标点的模型。

**Comment by yeyupiaoling** [comment]
应该是打开文件夹的时候报错，但看不出是什么问题
