### ISSUE TITLE
python train.py的时候报错

### ISSUE THREAD

**Issue by 2954456878** [yeyupiaoling/PPASR#158]
create_data.py已经执行完毕，也已经生成了
![3JIVME0G62 $30 Q2NGXBTJ](https://github.com/yeyupiaoling/PPASR/assets/88914706/1372f747-e8df-4ac3-8e43-bdc0a58e6896)
，执行train.py时报错
![LDBXXP40PKZ 3~E6 J0VC{M](https://github.com/yeyupiaoling/PPASR/assets/88914706/3f58b2f4-a980-4bc1-86fc-728cea95b09a)

**Comment by yeyupiaoling** [comment]
很明显你数据列表没有数据啊。你看一下你是不是生成的时候有失败或者哪里写错了？

**Comment by 2954456878** [comment]
> 很明显你数据列表没有数据啊。你看一下你是不是生成的时候有失败或者哪里写错了？

![image](https://github.com/yeyupiaoling/PPASR/assets/88914706/6fdb9172-dc82-4db4-b43b-0cf253f1ba7c)
数据列表 都是正常生成的呀，也有url和text，音频文件也对的上

**Comment by yeyupiaoling** [comment]
你是不是存放错误路径了，你看一下。或者你手动打印看一下。

**Comment by 2954456878** [comment]
已解决，是音频长度的问题，超过了初始设置的max_duration：20
