### ISSUE TITLE
如何调用模型实时识别语音

### ISSUE THREAD

**Issue by ftdzh1994** [yeyupiaoling/PPASR#16]
更新日志中提到「2021.11.30: 全面修改为流式语音识别模型」，那应该能支持实时的语音识别？

是否有相应的调用代码提供参考，谢谢🙏

**Comment by yeyupiaoling** [comment]
这个是示例代码，还不完善：
https://github.com/yeyupiaoling/PPASR/blob/8a489b36ee314b9e3922ec8f4b3583c02741935e/infer_path.py#L62-L83
