### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by yourengod** [yeyupiaoling/PPASR#163]
训练的时候出现这个问题：怎么解决？
![image](https://github.com/yeyupiaoling/PPASR/assets/6347733/cbc62284-2c1f-4dd3-9e2d-164a943a862c)

**Comment by yeyupiaoling** [comment]
cuda没配置好，看我文档用conda安装paddlepaddle

**Comment by yourengod** [comment]
我安装的cuda是11.7 cudnn是cudnn-linux-x86_64-8.9.2.26_cuda11-archive.tar
paddle:python3 -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by yourengod** [comment]
conda install paddlepaddle-gpu==2.4.1 cudatoolkit==11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
安装后还是那个问题，我是在ppasr源码上train的，请指教一下？

**Comment by yeyupiaoling** [comment]
最新的是2.5.0

**Comment by yourengod** [comment]
2.5.0报这个错误：
W0725 15:22:10.749516 73697 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 5.2, Driver API Version: 12.2, Runtime API Version: 11.7
W0725 15:22:10.750409 73697 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    trainer.train(save_model_path=args.save_model_path,
  File "/data/zhdp/PPASR/ppasr/trainer.py", line 478, in train
    self.__setup_model(input_dim=self.test_dataset.feature_dim,
  File "/data/zhdp/PPASR/ppasr/trainer.py", line 156, in __setup_model
    summary(self.model, inputs=[paddle.rand([1, 260, self.train_dataset.feature_dim]),
  File "/data/zhdp/PPASR/ppasr/utils/model_summary.py", line 118, in summary
    result, params_info = summary_string(net, _input_size, dtypes, inputs)
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/data/zhdp/PPASR/ppasr/utils/model_summary.py", line 249, in summary_string
    model(*x)
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/zhdp/PPASR/ppasr/model_utils/conformer/model.py", line 89, in forward
    encoder_out, encoder_mask = self.encoder(speech, speech_lengths)
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1256, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1235, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/zhdp/PPASR/ppasr/model_utils/conformer/encoder.py", line 186, in forward
    masks = make_non_pad_mask(xs_lens).unsqueeze(1)  # (B, 1, L)
  File "/data/zhdp/PPASR/ppasr/model_utils/utils/mask.py", line 68, in make_non_pad_mask
    return make_pad_mask(lengths).logical_not()
  File "/data/zhdp/PPASR/ppasr/model_utils/utils/mask.py", line 40, in make_pad_mask
    seq_range_expand = seq_range.unsqueeze(0).expand([batch_size, max_len])
  File "/data/anaconda3/envs/asr/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3443, in expand
    return _C_ops.expand(x, shape)
ValueError: (InvalidArgument) The 1th element of 'shape' for expand_v2 op must be greater than 0, but the value given is 0.
  [Hint: Expected expand_shape[i] > 0, but received expand_shape[i]:0 <= 0:0.] (at ../paddle/phi/infermeta/unary.cc:1039)

**Comment by yourengod** [comment]
![1690270569650](https://github.com/yeyupiaoling/PPASR/assets/6347733/03ec1f06-487b-4f26-a693-b5ce98a72761)
请教一下？

**Comment by yourengod** [comment]
我用的是ubuntu 20。ubuntu 18 过期了。

**Comment by yourengod** [comment]
我现还在用的ppasr是开发版本的，是最新的

**Comment by yourengod** [comment]
![1690272092249](https://github.com/yeyupiaoling/PPASR/assets/6347733/f9665698-c0e4-4967-b7f3-aea77fcd4a9c)

**Comment by yeyupiaoling** [comment]
你我看是不是显存不足

**Comment by yourengod** [comment]
![1690272092249](https://github.com/yeyupiaoling/PPASR/assets/6347733/c24ab70d-e2d8-4b43-8e7a-6026bd0847c7)
这个新版本的问题。
![1690272333491](https://github.com/yeyupiaoling/PPASR/assets/6347733/314f8029-aba2-4df2-8cb8-4a376ce76ab9)
这个问题是原先的版本的问题。定位如下图：
![1690272471593](https://github.com/yeyupiaoling/PPASR/assets/6347733/8049e1ae-672c-4785-b8a2-5413a1b46d8c)
nvidia-smi命令如下：
![1690272523103](https://github.com/yeyupiaoling/PPASR/assets/6347733/83d3887c-ce34-40b0-8577-c1f2eaaa5195)
请教请教

**Comment by yourengod** [comment]
![1690274953266](https://github.com/yeyupiaoling/PPASR/assets/6347733/b8701612-592a-4e1a-951c-307015e2cb2c)
这里出的问题，max_len=0，这个怎么一回事啊？请教请教。

**Comment by yeyupiaoling** [comment]
你换个显卡看一下吧，我看你显卡的计算能力很低，不知道是不是老版本的显卡问题？

**Comment by yourengod** [comment]
好的，我试一试

**Comment by yeyupiaoling** [comment]
问一下你数据列表里面有数据吗？

**Comment by yourengod** [comment]
![1690340095654](https://github.com/yeyupiaoling/PPASR/assets/6347733/011efe0a-68af-4f49-8de0-40e022829d7f)
是这个吧？

**Comment by yourengod** [comment]
GPU Compute Capability: 8.6,这个可以。

**Comment by yourengod** [comment]
请教一个问题。https://download.csdn.net/download/qq_33200967/86951249，这个地址的模型是不能用于再训练的是吗？我需要一个好的预训练的模型。

**Comment by yourengod** [comment]
请教一个问题。你提供的这个[地址](https://download.csdn.net/download/qq_33200967/86951249)的模型是不是不能用于再训练？我试了一下，出个错。我需要一个好的预训练的模型。

**Comment by yeyupiaoling** [comment]
> ![1690340095654](https://github.com/yeyupiaoling/PPASR/assets/6347733/011efe0a-68af-4f49-8de0-40e022829d7f)
> 是这个吧？

你这个是字典。

**Comment by yeyupiaoling** [comment]
> GPU Compute Capability: 8.6,这个可以。

可以是吧，那就没有问题。

**Comment by yeyupiaoling** [comment]
> 请教一个问题。你提供的这个[地址](https://download.csdn.net/download/qq_33200967/86951249)的模型是不是不能用于再训练？我试了一下，出个错。我需要一个好的预训练的模型。

 我提供的这个是一训练模型，你可以当做一训练模型去加载，但是要把配置文件一起复制进去。

**Comment by yourengod** [comment]
> > 请教一个问题。你提供的这个[地址](https://download.csdn.net/download/qq_33200967/86951249)的模型是不是不能用于再训练？我试了一下，出个错。我需要一个好的预训练的模型。
> 
> 我提供的这个是一训练模型，你可以当做一训练模型去加载，但是要把配置文件一起复制进去。

我要是没有记错的话，里面好像有这些，
![1690422739839](https://github.com/yeyupiaoling/PPASR/assets/6347733/5cabd619-81bc-490c-b0f0-f0838106ca56)
配制文件用的这个：“configs/conformer_online_zh.yml”
请问我该如何把它做为预训练模型加载使用？

**Comment by yeyupiaoling** [comment]
微调不用这些，另外你下载的模型是旧的

**Comment by yourengod** [comment]
“https://download.csdn.net/download/qq_33200967/86951249”这个是新的是吗？新的可以再训练是吗？我需要填加领域术语语料。

**Comment by yourengod** [comment]
> 微调不用这些，另外你下载的模型是旧的

https://download.csdn.net/download/qq_33200967/86951249 这个是新的，是吗？新的可以再训练是吗？我需要填加领域术语语料。

**Comment by yeyupiaoling** [comment]
是的，这个如果你在上面下的是最新的。你可以用这个异性的模型来微调你的数据提高你数据的准确率。

**Comment by yourengod** [comment]
> 是的，这个如果你在上面下的是最新的。你可以用这个异性的模型来微调你的数据提高你数据的准确率。

多谢，我试一试。另外，有个小问题，如何指定多个gpu啊，这样 CUDA_VISIBLE_DEVICES=a,b,c  python train.py ，我咋觉得没有用啊，老是内存溢出，我改了批大小16也没有用。

**Comment by yeyupiaoling** [comment]
看文档。

**Comment by yourengod** [comment]
你的那个新模型，我下载下来了，用了一下，出了下面的问题。设置是这样：
add_arg('resume_model',     str,    './models/conformer_streaming_fbank/best_model/',                       '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str,    './models/conformer_streaming_fbank/best_model/',      
请教一下怎么办？
![image](https://github.com/yeyupiaoling/PPASR/assets/6347733/46ea566d-ca0d-4f56-9c99-c563fc69f5f3)

**Comment by yeyupiaoling** [comment]
下载的模只能用于预训练的，不能用于恢复训练

**Comment by yourengod** [comment]
> 下载的模只能用于预训练的，不能用于恢复训练

只能用于预训练，怎么设置啊？

**Comment by yeyupiaoling** [comment]
> > 下载的模只能用于预训练的，不能用于恢复训练
> 
> 只能用于预训练，怎么设置啊？

add_arg('pretrained_model', str,    None,                       '预训练模型的路径，当为None则不使用预训练模型')

**Comment by yourengod** [comment]
> > > 下载的模只能用于预训练的，不能用于恢复训练
> > 
> > 
> > 只能用于预训练，怎么设置啊？
> 
> add_arg('pretrained_model', str, None, '预训练模型的路径，当为None则不使用预训练模型')

这样？？？
add_arg('resume_model',     str,    None,                       '恢复训练，当为None则不使用预训练模型')
add_arg('pretrained_model', str,    './models/conformer_streaming_fbank/best_model/',        

还有我下面就是按照doc里面说的进行数据处理，然后就是train就可以了吧？

**Comment by yeyupiaoling** [comment]
嗯嗯

**Comment by yourengod** [comment]
> add_arg('resume_model', str, None, '恢复训练，当为None则不使用预训练模型')

add_arg('resume_model', str, None, '恢复训练，当为None则不使用预训练模型')
这个是中断训练后，要恢复训练，让程序加载最新训练且保存的模型用的吗？

**Comment by yourengod** [comment]
你好，如果我在你的模型上接着训练必须用你的这个词表文件“vocabulary.txt”吧，请问如何填加新词？

**Comment by yeyupiaoling** [comment]
是的，

**Comment by yourengod** [comment]
> 是的，


这个词表文件“vocabulary.txt”，请问如何往里面添加新词？

**Comment by yeyupiaoling** [comment]
那就生成自己字典。模型当预训练模型使用

**Comment by yourengod** [comment]
> 那就生成自己字典。模型当预训练模型使用

那预训练模型跟新生成的字典中的字对应不上吧？
