### ISSUE TITLE
download_data/noise.py 这个里面”args.noise_path”这个不存在？

### ISSUE THREAD

**Issue by yourengod** [yeyupiaoling/PPASR#166]
![image](https://github.com/yeyupiaoling/PPASR/assets/6347733/5f397682-51df-4e83-a017-9a91e093b8d6)

**Comment by yeyupiaoling** [comment]
可能是个bug，我有空修复一下。

**Comment by yourengod** [comment]
> 可能是个bug，我有空修复一下。

https://github.com/yeyupiaoling/PPASR/blob/r1.x/download_data/noise.py 这里有

**Comment by yeyupiaoling** [comment]
是个bug，有空修复一下，或者你也可以提一个pr

**Comment by yourengod** [comment]
> 是个bug，有空修复一下，或者你也可以提一个pr

我拉下来修正了一下，提交了。但不知道是不是这样处理。另外，我想请教“语言模型”是怎么搞出来的？就这个“  language_model_path: 'lm/zh_giga.no_cna_cmn.prune01244.klm'。这有点像kenlm。
”

**Comment by yeyupiaoling** [comment]
@yourengod 我没有收到提交。
就是kenlm。你看文档可以知道怎么生成的。
