### ISSUE TITLE
请问如何支持microphone输入的流式语音识别？

### ISSUE THREAD

**Issue by zhaokaien** [yeyupiaoling/PPASR#169]
请问如何支持microphone输入的流式语音识别，谢谢！

**Comment by zjx1804842918** [comment]
请问进阶版支持CPU跑吗？

**Comment by yeyupiaoling** [comment]
@zhaokaien 可以参考这个：https://github.com/yeyupiaoling/PPASR/blob/release/2.4.x/infer_gui.py

**Comment by yeyupiaoling** [comment]
>请问进阶版支持CPU跑吗？

@zjx1804842918 好像可以吧，太久了，最新版本的可以，修改参数就可以
