### ISSUE TITLE
ImportError: DLL load failed while importing _pynini: 内存资源不足，无法处理此命令。

### ISSUE THREAD

**Issue by enfuliu** [yeyupiaoling/PPASR#171]
您好！我在windows平台上运行create_data.py的时候，报ImportError: DLL load failed while importing _pynini: 内存资源不足，无法处理此命令的错误。请问是内存不足还是其他的原因呢？有没有参数可以进行调节？

**Comment by yeyupiaoling** [comment]
好像是pynini的错误，可以使用conda install pynini -c forge-conda 重新安装
