### ISSUE TITLE
预测报错，Axis should be less than 3

### ISSUE THREAD

**Issue by rongp** [yeyupiaoling/PPASR#175]
![图片1](https://github.com/yeyupiaoling/PPASR/assets/5117451/987d6ea8-7d53-4e58-8496-0bfd85fca839)

**Comment by yeyupiaoling** [comment]
@rongp 模型输入有问题，你看看有的音频有没有问题？如果你的是下载的模型，需要把全部文件复制到项目根目录，替换掉原的文件。
