### ISSUE TITLE
paddlespeech_ctcdecoders安装不了

### ISSUE THREAD

**Issue by SSTato** [yeyupiaoling/PPASR#177]
centos7、python3.11.7下安装 python -m pip install paddlespeech_ctcdecoders -U -i https://ppasr.yeyupiaoling.cn/pypi/simple/后，import paddlespeech_ctcdecoders失败，pip list看是安装上了。
File "/home/ai/anaconda3/envs/chat-0.2.10/lib/python3.11/site-packages/ppasr/decoders/swig_wrapper.py", line 1, in <module>
    import paddlespeech_ctcdecoders
ModuleNotFoundError: No module named 'paddlespeech_ctcdecoders'
>>> import paddlespeech_ctcdecoders
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'paddlespeech_ctcdecoders'

在window10、python3.11.0是没问题的，python3.11/site-packages文件夹下有paddlespeech_ctcdecoders-0.2.2.dist-info和paddlespeech_ctcdecoders.py。但是去centos7的python3.11/site-packages下看只有paddlespeech_ctcdecoders-0.2.2.dist-info这个文件夹，这是为什么，直接安装(https://ppasr.yeyupiaoling.cn/pypi/simple/paddlespeech-ctcdecoders/paddlespeech_ctcdecoders-0.2.2-cp311-cp311-linux_x86_64.whl)这个whl文件也不行。

**Comment by SSTato** [comment]
centos7中python3.10.13是可以的，应该是python版本的问题吧

**Comment by yeyupiaoling** [comment]
对的，不支持3:11。
