### ISSUE TITLE
不支持中英文夹杂吗，比如”我选的是B选项“，英文识别不出来

### ISSUE THREAD

**Issue by JiYueBo666** [yeyupiaoling/PPASR#179]

**Comment by yeyupiaoling** [comment]
你用的是那个模型，如果是训练了wenetspeech数据集应该是可以的

**Comment by JiYueBo666** [comment]
> 你用的是那个模型，如果是训练了wenetspeech数据集应该是可以的

我使用的是您预训练的deepspeech2

**Comment by JiYueBo666** [comment]
> 你用的是那个模型，如果是训练了wenetspeech数据集应该是可以的

是wenetsseech的数据集训练的deepspeach2，英文识别效果很差，大部分情况下识别不到

**Comment by yeyupiaoling** [comment]
wenetsseech这数据集的英文不多，所以效果差。
