### ISSUE TITLE
为何训练模型时loss突然变为nan

### ISSUE THREAD

**Issue by panliang5020** [yeyupiaoling/PPASR#18]
我最近在尝试训练PPASR模型,使用了WenetSpeech数据集和Aishell，Free ST-Chinese-Mandarin-Corpus，THCHS-30数据集,但是在训练过程中loss突然变为nan,训练依旧进行,我有调低学习率,但是没什么用,我应该怎么确定目前情况发生的原因呢,这是我训练时的参数配置
我是在有GPU卡的docker内进行的单卡训练
```
-----------  Configuration Arguments -----------
alpha: 2.2
augment_conf_path: conf/augmentation.json
batch_size: 128
beam_size: 300
beta: 4.3
cutoff_prob: 0.99
cutoff_top_n: 40
dataset_vocab: dataset/vocabulary.txt
decoder: ctc_beam_search
lang_model_path: lm/zhidao_giga.klm
learning_rate: 5e-05
max_duration: 20
mean_std_path: dataset/mean_std.npz
min_duration: 0.5
num_epoch: 65
num_proc_bsearch: 10
num_workers: 6
pretrained_model: None
resume_model: None
save_model_path: models/
test_manifest: dataset/manifest.test
train_manifest: dataset/manifest.train
use_model: deepspeech2
------------------------------------------------
```
下面图片是训练时loss变为nan
<img width="872" alt="1" src="https://user-images.githubusercontent.com/51695693/147178347-6f54735c-8bea-4fdb-bb75-3166bf45b6a1.png">

**Comment by yeyupiaoling** [comment]
你有自己生成词汇表吗？

**Comment by panliang5020** [comment]
> 你有自己的生成词汇表吗？

你是指通过你写的create_data.py文件生成的vocabulary.txt文件吗

**Comment by yeyupiaoling** [comment]
是的，

**Comment by panliang5020** [comment]
> 是的，

有的,这是代码运行生成的vocabulary.txt文件,生成后存放于dataset文件下,我并没有修改
[vocabulary.txt](https://github.com/yeyupiaoling/PPASR/files/7766290/vocabulary.txt)

**Comment by yeyupiaoling** [comment]
按道理，WenetSpeech数据集和Aishell，Free ST-Chinese-Mandarin-Corpus，THCHS-30数据集, 这几个数据词汇表的字符应该有6000多字符才对，你的怎么只有5000多

**Comment by panliang5020** [comment]
> 按道理，WenetSpeech数据集和Aishell，Free ST-Chinese-Mandarin-Corpus，THCHS-30数据集, 这几个数据词汇表的字符应该有6000多字符才对，你的怎么只有5000多

生成训练集后我就开始进行训练模型了,并没有对生成的数据进行修改,那我现在是否应该再生成一次训练集数据

**Comment by yeyupiaoling** [comment]
我发我的给你试试
[vocabulary.txt](https://github.com/yeyupiaoling/PPASR/files/7766388/vocabulary.txt)

**Comment by yeyupiaoling** [comment]
你看看你的数据列表是不是从小到大排序的

**Comment by panliang5020** [comment]
> 我发我的给你试试 [vocabulary.txt](https://github.com/yeyupiaoling/PPASR/files/7766388/vocabulary.txt)

我更换你给的词汇表后再次尝试训练loss依旧会变nan
<img width="872" alt="2" src="https://user-images.githubusercontent.com/51695693/147184490-47870f2b-10f1-4901-890a-7042da27eee0.png">

**Comment by panliang5020** [comment]
> 你看看你的数据列表是不是从小到大排序的

不是很理解您说的数据列表指的是哪一个,但是我打印了input_lens发现他是从大到小的

**Comment by yeyupiaoling** [comment]
manifest.train
这个文件，看里面的时长

**Comment by panliang5020** [comment]
> manifest.train 这个文件，看里面的时长

时长是从小到大的排序,不过在liunx下显示的中文字符显示有点问题,在windows下这些字符是正常的
<img width="818" alt="30" src="https://user-images.githubusercontent.com/51695693/147187842-2dc62e1b-f449-485c-879e-5587ebc91d1f.png">

**Comment by yeyupiaoling** [comment]
你的数据列表有问题啊，请检查下，我用的都是utf-8，不应该出现乱码才对。
是不是因为docker显示的原因。
如果列表本身没有问题，那应该是没问题的。
你batch size 减少到64试试

**Comment by panliang5020** [comment]
> 你的数据列表有问题啊，请检查下，我用的都是utf-8，不应该出现乱码才对。 是不是因为docker显示的原因。 如果列表本身没有问题，那应该是没问题的。 你batch size 减少到64试试

不是的,这个是vim编辑器的问题,使用cat或者tail显示的中文也是正确的.刚才试了64.现在准备调到32

**Comment by yeyupiaoling** [comment]
你有没有修改哪里？

**Comment by panliang5020** [comment]
> 你有没有修改哪里？

我更换了解码策略,使用了ctc_beam_search,更换了语言模型,使用比较大的模型zhidao_giga.klm,然后就是对batch_size和num_worker的调整,当然最新的一次尝试已经分别换成了32和8的最初配置,关于ctc_loss我有考虑使用torch.nn.CTCloss解决loss为nan的情况,但是发现输入的矩阵不一致需要调整所以放弃了,唯一可能有点区别的是我使用的paddle版本是2.1.3不知道是否有影响,其他就是按流程走下来的没有修改,我觉得是否是我数据生成的有问题或许我应该再生成一次

**Comment by yeyupiaoling** [comment]
解码策略只是在推理时用到，这不会影响到训练。但是我建议训练是用ctc_greedy，这样快。

你最想尝试的batch_size=32，结果怎么样？

要不你安装2.2.0版本试试？

如果安装新版本还是不行，create_data.py重新生成下数据

**Comment by panliang5020** [comment]
> 解码策略只是在推理时用到，这不会影响到训练。但是我建议训练是用ctc_greedy，这样快。
> 
> 你最想尝试的batch_size=32，结果怎么样？
> 
> 要不你安装2.2.0版本试试？
> 
> 如果安装新版本还是不行，create_data.py重新生成下数据

还是不行,依旧会变nan,接下来我会尝试更换paddle版本和重新生成数据.
<img width="854" alt="40" src="https://user-images.githubusercontent.com/51695693/147207213-a99f3118-f2f0-4efe-a531-1c03b69afc0f.png">

**Comment by yeyupiaoling** [comment]
嗯嗯，2.2.0版本的CTCLoss有改动的。

**Comment by panliang5020** [comment]
> 嗯嗯，2.2.0版本的CTCLoss有改动的。

确实是版本的问题,在更换版本2.2.0后目前没有出现loss变nan的情况了,非常感谢.
另外使用batch_size=32搭配num_work=8的组合训练的时间有点长了,几乎要一个多月,但是我在调大batch时经常会出现/dev/shm文件夹存储不够的error,这是docker启动时分配的内存,不太方便调整,目前我只有64m的内存空间,不知道您之前有没有类似情况

**Comment by yeyupiaoling** [comment]
在这个函数上加参数：`use_shared_memory=True`

https://github.com/yeyupiaoling/PPASR/blob/889a7f2d8dfd7c604bf4d5990f4dd08ace5ef08c/ppasr/trainer.py#L227

**Comment by yeyupiaoling** [comment]
@panliang5020 
怎么样，速度有加快吗？
你训练完要多久？
 也不用等他训练完，你看VisualDL图，如果收敛差不多就可以停止了，大概一半的时间就可以了。

**Comment by panliang5020** [comment]
> @panliang5020 怎么样，速度有加快吗？ 你训练完要多久？ 也不用等他训练完，你看VisualDL图，如果收敛差不多就可以停止了，大概一半的时间就可以了。

非常抱歉这么久才回复你,上次之后的训练依旧不顺利,docker内存限制问题严重,所以我换了新的docker,将数据重新下载解压,中间因为自己的失误操作,解压了两遍数据.
今天才开始正式的训练,不过训练速度依旧很慢,我调整了batch到256 ,num_worker为12,然后发现了些问题,首先gpu的内存越来越大,10000个batch的时候单卡的占用已经达到12个g,而总量才15g.
其次,多卡训练不成功,查看日志后发现报错:
**UnboundLocalError: local variable 'writer' referenced before assignment**,多可训练时没有定义这个变量

希望能听取您的意见

**Comment by yeyupiaoling** [comment]
安装最新的版本，也可以拉最新源码

支持pip安装
```
python -m pip install ppasr
```

**Comment by panliang5020** [comment]
> 安装最新的版本，也可以拉最新源码
> 
> 支持pip安装
> 
> ```
> python -m pip install ppasr
> ```

使用多卡训练可以解决gpu内存占用的问题吗,因为数据量的问题,才10000个batch已经达到12g,很担忧他一直增长下去

**Comment by yeyupiaoling** [comment]
显存一直增长的原因是：
第一个epoch数据的长度是从短到长排序的，越到后面，数据越长，显存就增大
后面的epoch都是随机打乱的

你只要保证数据最大的时候不oom就行了

**Comment by panliang5020** [comment]
> 显存一直增长的原因是： 第一个epoch数据的长度是从短到长排序的，越到后面，数据越长，显存就增大 后面的epoch都是随机打乱的
> 
> 你只要保证数据最大的时候不oom就行了

好的,非常感谢.
