### ISSUE TITLE
添加标点符号

### ISSUE THREAD

**Issue by harrisonpy** [yeyupiaoling/PPASR#180]
你好，我在寻找一个本地解决方案就是
我平时需要把文字自动添加标点符号在本地环境
看到的你的这个添加标点符号的项目，但是运行失败，请问具体使用哪个呢，只是输入文本输出带标点符号的，不需要别的。
能帮我提供个安装使用思路么
谢谢啦

**Comment by yeyupiaoling** [comment]
我这个就可以直接在本地运行的，你说的报错，报什么错误？
