### ISSUE TITLE
vocabulary.json下载

### ISSUE THREAD

**Issue by Yang-Changhui** [yeyupiaoling/PPASR#2]
你好，我想请问下vocabulary.json在哪里下载呢

**Comment by yeyupiaoling** [comment]
执行这里自动生成的，你看下文档在运行项目。
![微信截图_20210713143516](https://user-images.githubusercontent.com/26297768/125403191-d2e36300-e3e7-11eb-85fa-cbdb7fea510b.png)

**Comment by Yang-Changhui** [comment]
你好，打扰一下，我下载的数据集是data_thchs30，data文件下为wav和trn文件，请问需要把trn文件准换成txt文件吗，我运行create_manifest.py，显示RuntimeError: Error opening 'A11_0 ./A11_0.wav\n': System error.
我的配置为：
add_arg('--annotation_path',    str,  'dataset/data/',   '标注文件的路径')
add_arg('manifest_prefix',      str,  'dataset/train/',              '训练数据清单，包括音频路径和标注信息')
add_arg('is_change_frame_rate', bool, True,                    '是否统一改变音频为16000Hz，这会消耗大量的时间')
add_arg('count_threshold',      int,  0,                       '字符计数的截断阈值，0为不做限制')
add_arg('vocab_path',           str,  'dataset/zh_vocab.json',  '生成的数据字典文件')
add_arg('manifest_path',        str,  'dataset/manifest.train', '数据列表路径')
请问如何解决呢？麻烦您了
