### ISSUE TITLE
能否在已有模型的基础上加上自己的数据训练

### ISSUE THREAD

**Issue by AlisaChen98** [yeyupiaoling/PPASR#20]
想咨询下大佬，是否可以基于您wenet的模型再加上自己的数据来训练呢。是在trainer上把pretrained model指向您提供的预训练模型嘛～

**Comment by yeyupiaoling** [comment]
用这个参数。把下载的model.state 里面的epoch改为0，另外我没有提供wenet模型,

https://github.com/yeyupiaoling/PPASR/blob/0d4ca56d6c0db7923acb2570d87bae8b0695b900/train.py#L30

**Comment by AlisaChen98** [comment]
哦哦好滴 我以为您提供的那个基于超大数据集的model就是基于wenet做的

**Comment by yeyupiaoling** [comment]
那个不是，wenet数据有1万多小时呢

**Comment by AlisaChen98** [comment]
![image](https://user-images.githubusercontent.com/45112983/148715065-ec10f980-0ea6-4257-831f-23906a19a7f7.png)
您好，采用您说的方法出现了这个问题，想请教一下是什么原因呀

**Comment by yeyupiaoling** [comment]
epoch你修改成什么了？

**Comment by AlisaChen98** [comment]
> epoch你修改成什么了？

在best_model里将model.state中的last_epoch改成了0

**Comment by yeyupiaoling** [comment]
改成1吧 @AlisaChen98

**Comment by AlisaChen98** [comment]
> 改成1吧 @AlisaChen98
![image](https://user-images.githubusercontent.com/45112983/148731952-c38cbc06-4cdd-497a-acf0-6940ad2cbbd5.png)
改成1以后又出现了一个新的问题

**Comment by yeyupiaoling** [comment]
如你要恢复模型，要全部都是用我的文件，dataset里面的那两个

**Comment by AlisaChen98** [comment]
> 如你要恢复模型，要全部都是用我的文件，dataset里面的那两个

感谢！解决了
