### ISSUE TITLE
长音频文件识别不了问题

### ISSUE THREAD

**Issue by ghfyxw** [yeyupiaoling/PPASR#21]
请问下大佬，我用的是自己的wav上音频文件，但是总识别错误，用短音频识别可以，但是没有标点符号，然后demo里的长音频文件貌似没有了

**Comment by yeyupiaoling** [comment]
什么错误？本项目目前还不支持加标点符号

**Comment by ghfyxw** [comment]
Traceback (most recent call last):
File "infer_path.py", line 91, in <module>
predict_long_audio()
File "infer_path.py", line 42, in predict_long_audio
audios_bytes = crop_audio_vad(args.wav_path)
File "D:\ppasr\PPASR-master\ppasr\utils\audio_vad.py", line 122, in crop_audio_vad
audio, sample_rate = read_wave(audio_path)
File "D:\ppasr\PPASR-master\ppasr\utils\audio_vad.py", line 15, in read_wave
assert num_channels == 1
AssertionError
这个错误，然后我用的是[语音](https://cdn.duozhuan100.com/output_cut.wav)这个文件，用短音频来是没问题，就是有点识别不太正确，但是用长音频来就直接报这个错了

**Comment by yeyupiaoling** [comment]
这个报错是说音频通道数不等于1，也就是不是单通道。你要转换为单通道才行。

**Comment by yeyupiaoling** [comment]
这么短的语音，直接用短语音识别就好。小于30秒的都可以使用短语音识别

**Comment by ghfyxw** [comment]
我是看到介绍长语音会有逗号间隔，就想用这个测试一下的，大神后面会上线有逗号间隔的版本吗

**Comment by yeyupiaoling** [comment]
会有，不过也行会很久

**Comment by ghfyxw** [comment]
大神还有个问题，就是我在训练模型的中途被外界原因给中断了，重新开始训练的话，是从头开始还是从断的地方开始呢

**Comment by yeyupiaoling** [comment]
会自动加载上一次保存的模型的
