### ISSUE TITLE
使用GPU，会卡住很久最终报Process finished with exit code -1073741819 (0xC0000005)终止程序

### ISSUE THREAD

**Issue by xk-777** [yeyupiaoling/PPASR#22]
E:\Users\ikun\anaconda3\envs\speech\python.exe E:/Users/ikun/PycharmProjects/Speech_AI/MASR-master/infer_path.py
E:\Users\ikun\anaconda3\envs\speech\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
-----------  Configuration Arguments -----------
alpha: 2.2
beam_size: 30
beta: 4.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoder: ctc_beam_search
is_long_audio: False
lang_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
model_path: models/deepspeech2/inference.pt
real_time_demo: False
to_an: False
use_gpu: True
use_model: deepspeech2
vocab_path: dataset/vocabulary.txt
wav_path: ./dataset/040.wav
------------------------------------------------

==================================================================
缺少 paddlespeech-ctcdecoders 库，请根据文档安装，如果是Windows系统，只能使用ctc_greedy。
【注意】已自动切换为ctc_greedy解码器。
==================================================================

W0111 22:20:02.530877  1384 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead.

Process finished with exit code -1073741819 (0xC0000005)

**Comment by yeyupiaoling** [comment]
你知道是哪一行报错吗？应该是你环境有问题吧

**Comment by yeyupiaoling** [comment]
你有测试过你的PaddlePaddle环境是否能正常使用吗？

**Comment by yeyupiaoling** [comment]
已私聊解决

**Comment by zyd-123** [comment]
==================================================== =======ct- ====
ctc_===cdlespeechdecoders库，根据如果，如果是Windows系统，使用_greedy。
【注意】已切换为ctc_greedy解码器。

请问如何解决的
