### ISSUE TITLE
能不能提供下Nvidia Jetson下3.7的PaddlePaddle的Inference预测库？

### ISSUE THREAD

**Issue by cgisky** [yeyupiaoling/PPASR#23]
py3.6安装lac 有点问题

**Comment by cgisky** [comment]
Collecting lac
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/88/966e99c95cac93730a7f3cdf92a17e2a0e924bea61b9a86ae7995feaa4fe/LAC-2.1.2.tar.gz (64.8 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnf33qhr/lac_ba44a9d658124b649bb5b918e576359a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnf33qhr/lac_ba44a9d658124b649bb5b918e576359a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b4xlyalf
       cwd: /tmp/pip-install-pnf33qhr/lac_ba44a9d658124b649bb5b918e576359a/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/c3/88/966e99c95cac93730a7f3cdf92a17e2a0e924bea61b9a86ae7995feaa4fe/LAC-2.1.2.tar.gz#sha256=22fcde0d5082d2044205ea6f6a7a9cd1f0d63e7b21b2dd5c9c73f27e7c0a3ef1 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.

**Comment by cgisky** [comment]
源码编译也不行~  好像AVX 相关

**Comment by yeyupiaoling** [comment]
你单独安装这个库试试看

**Comment by cgisky** [comment]
一样的  会降版本一个一个的装

**Comment by cgisky** [comment]
(py3.6) cgisky@cgisky-jetsonnano:~$ pip3 install lac -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting lac
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/88/966e99c95cac93730a7f3cdf92a17e2a0e924bea61b9a86ae7995feaa4fe/LAC-2.1.2.tar.gz (64.8 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_a488bda3eda84fa793d71f88fb637c2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_a488bda3eda84fa793d71f88fb637c2d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2l72io38
       cwd: /tmp/pip-install-lvygp58s/lac_a488bda3eda84fa793d71f88fb637c2d/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/c3/88/966e99c95cac93730a7f3cdf92a17e2a0e924bea61b9a86ae7995feaa4fe/LAC-2.1.2.tar.gz#sha256=22fcde0d5082d2044205ea6f6a7a9cd1f0d63e7b21b2dd5c9c73f27e7c0a3ef1 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/52/19/55bb532621c1e56b860794c9c86851a4ac744610c646a1ca9499e42f5773/LAC-2.1.1.tar.gz (64.8 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_d91036014a81457d8f101c94d3f918f1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_d91036014a81457d8f101c94d3f918f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wie12ckw
       cwd: /tmp/pip-install-lvygp58s/lac_d91036014a81457d8f101c94d3f918f1/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/52/19/55bb532621c1e56b860794c9c86851a4ac744610c646a1ca9499e42f5773/LAC-2.1.1.tar.gz#sha256=9c2feacd28c8e963f74a0d5d3dfa3d698e1b5df6136e727c08b9e7f4d7241a6a (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fb/4b/a98bdeea4b66268da82500fbc6696c06ff20673a453fe66c1a30742ae31c/LAC-2.1.0.tar.gz (64.8 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_0b26d6d48ce0438b8b059f70fa8fe656/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_0b26d6d48ce0438b8b059f70fa8fe656/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e5xo1y4j
       cwd: /tmp/pip-install-lvygp58s/lac_0b26d6d48ce0438b8b059f70fa8fe656/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/fb/4b/a98bdeea4b66268da82500fbc6696c06ff20673a453fe66c1a30742ae31c/LAC-2.1.0.tar.gz#sha256=bd1d8089799cc8a6224b7ebb002079c26628fa5f8bc89a7b491dda9134f636e1 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/00/cf/36bbbfbeec33f40978c865ad9b899ab3dbed588a5f2b1bfdf5c363834c03/LAC-2.0.5.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_7b0e1317355143b7bb937e5524c8efaa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_7b0e1317355143b7bb937e5524c8efaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jb_jetgd
       cwd: /tmp/pip-install-lvygp58s/lac_7b0e1317355143b7bb937e5524c8efaa/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/00/cf/36bbbfbeec33f40978c865ad9b899ab3dbed588a5f2b1bfdf5c363834c03/LAC-2.0.5.tar.gz#sha256=30dd4823ec2c9bc83e621d2cff2c1f116c22d6e7b0f884589d07f9630c88faa0 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a9/1c/c8e14f3bba95fa880fd9f5fcc58bc4afd3b310672276e64b1ac41bf4bbd2/LAC-2.0.4.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_d331bb922dfb4012bbd8cbe78e197914/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_d331bb922dfb4012bbd8cbe78e197914/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1i0pzpzm
       cwd: /tmp/pip-install-lvygp58s/lac_d331bb922dfb4012bbd8cbe78e197914/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/a9/1c/c8e14f3bba95fa880fd9f5fcc58bc4afd3b310672276e64b1ac41bf4bbd2/LAC-2.0.4.tar.gz#sha256=375fa7097d90ac40f6979de0aedaef4b4353c498fcee5c4f3d2ff8fa3b65be3c (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cc/d7/6d88cd4d18cf2b99ee14aa3339b8520b6843e9579b5076bcbceb58c31472/LAC-2.0.3.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_432e0f72d8254797ba759f321a244fd0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_432e0f72d8254797ba759f321a244fd0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q2xazuf4
       cwd: /tmp/pip-install-lvygp58s/lac_432e0f72d8254797ba759f321a244fd0/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/cc/d7/6d88cd4d18cf2b99ee14aa3339b8520b6843e9579b5076bcbceb58c31472/LAC-2.0.3.tar.gz#sha256=f254fd33891a2e57b682d650342c8db2a5209929de7fa7ce714d6dc956fbfba8 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e1/0b/1eedf702e87b0daf675f68053d43bd1f2a6880a916c403ddbddf9d7636c3/LAC-2.0.2.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_25f41ace00a64608a79d9e08dcccca50/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_25f41ace00a64608a79d9e08dcccca50/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3lb0ohv_
       cwd: /tmp/pip-install-lvygp58s/lac_25f41ace00a64608a79d9e08dcccca50/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/e1/0b/1eedf702e87b0daf675f68053d43bd1f2a6880a916c403ddbddf9d7636c3/LAC-2.0.2.tar.gz#sha256=b3c77384daeecf508ba02b48438872936af691b6866d2ea779e3a532d013c620 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/79/26/f7463f6775a143439f8a8d3671a6704e35e30fcefca16a14857a5a482918/LAC-2.0.1.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_d5ed3b7858364d4dbfba325e10636506/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_d5ed3b7858364d4dbfba325e10636506/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qwfmbf0j
       cwd: /tmp/pip-install-lvygp58s/lac_d5ed3b7858364d4dbfba325e10636506/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/79/26/f7463f6775a143439f8a8d3671a6704e35e30fcefca16a14857a5a482918/LAC-2.0.1.tar.gz#sha256=66efbf9460bc0b3f930573cc14357d07b9cf7282a233007cb3a3e0cd471814ec (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/70/a0/f884d64e825b47b6319ed78b4ff6b10a689770c04733a98a4ad321e67c36/LAC-2.0.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_8ba2c245f6404c4ba00b544f04c91573/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_8ba2c245f6404c4ba00b544f04c91573/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sb_8i6rd
       cwd: /tmp/pip-install-lvygp58s/lac_8ba2c245f6404c4ba00b544f04c91573/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/70/a0/f884d64e825b47b6319ed78b4ff6b10a689770c04733a98a4ad321e67c36/LAC-2.0.0.tar.gz#sha256=468cf42db487fb4c39593bcce180ecbf128b764cad1d6a51d6e583c23983a934 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e2/fb/ef2667f863332384bc0e35a008f58e3f9278004a7be3d393f74df7da2e56/LAC-0.1.5.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_7454b999bea6427b8af7f1610040ae15/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_7454b999bea6427b8af7f1610040ae15/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-62mr6y_7
       cwd: /tmp/pip-install-lvygp58s/lac_7454b999bea6427b8af7f1610040ae15/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/e2/fb/ef2667f863332384bc0e35a008f58e3f9278004a7be3d393f74df7da2e56/LAC-0.1.5.tar.gz#sha256=93ba5a1b8f074c2e5ad7ab562b6f4b2b123ab026b4c4c0423c26b773742e6041 (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/af/69/baa65c1c57c21fec75e574d4dd5813ac4c201b648afe1af9da1a721d1bfc/LAC-0.1.4.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_480916d73d674b5ba09e597a4aa0c660/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_480916d73d674b5ba09e597a4aa0c660/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5bm5vepj
       cwd: /tmp/pip-install-lvygp58s/lac_480916d73d674b5ba09e597a4aa0c660/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/af/69/baa65c1c57c21fec75e574d4dd5813ac4c201b648afe1af9da1a721d1bfc/LAC-0.1.4.tar.gz#sha256=ea9b2316870650f15e9610faacbef1978fea94161f16904fc3fdf8addb9166ce (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4c/ae/177ed3514addecc1da5b213065dab94d77e28423664e96343c4f488424eb/LAC-0.1.3.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_80ecd37410274926b64cea3aeda6e12a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_80ecd37410274926b64cea3aeda6e12a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-07cestlg
       cwd: /tmp/pip-install-lvygp58s/lac_80ecd37410274926b64cea3aeda6e12a/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/4c/ae/177ed3514addecc1da5b213065dab94d77e28423664e96343c4f488424eb/LAC-0.1.3.tar.gz#sha256=1b416ec143a8f45028c0f7cb92a4724f1857ba433db31e84b5d9732c21e0721d (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/74/e9/5bf622b5d5d50d24aefe72d75dd1e1b6387a9353f7a89325dac1e12a02f2/LAC-0.1.2.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /home/cgisky/.virtualenvs/py3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lvygp58s/lac_43984dbca72c4707b1a4d7c2c5aa6b8a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lvygp58s/lac_43984dbca72c4707b1a4d7c2c5aa6b8a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n7wrwqne
       cwd: /tmp/pip-install-lvygp58s/lac_43984dbca72c4707b1a4d7c2c5aa6b8a/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/74/e9/5bf622b5d5d50d24aefe72d75dd1e1b6387a9353f7a89325dac1e12a02f2/LAC-0.1.2.tar.gz#sha256=ed6c0feae58841d7980e95ac0c2dcfd4f6c9d7595757561a192c74b87b24fefc (from https://pypi.tuna.tsinghua.edu.cn/simple/lac/). Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
^C^Z
[1]+  已停止

**Comment by yeyupiaoling** [comment]
你 不用虚拟环境试试，用同学是可以的。

**Comment by cgisky** [comment]
嗯 不用虚拟环境 可以了

**Comment by yeyupiaoling** [comment]
好的
