### ISSUE TITLE
train的时候最后一层linear的输入shape问题

### ISSUE THREAD

**Issue by 519994824** [yeyupiaoling/PPASR#27]
**AssertionError: Variable Shape not match, Variable [ linear_0.w_0_moment1_0 ] need tensor with shape (1024, 563) but load set tensor with shape (1024, 564)**
create_data.py后词表vocab是563，但是开始训练后第一个epoch就报错，继续往下找
python3.7/site-packages/paddle/fluid/dygraph/layers.py中 _check_match(key, param)方法中发现，state_dict.get(key, None)在key=output.bias和output.weight的时候shape是564，但for key, param in self.state_dict().items():的最后几个param中的shape又是词表的563，所以导致了冲突
求大佬帮忙看看，感激不尽

**Comment by yeyupiaoling** [comment]
你有使用预训练模型吗？

**Comment by yeyupiaoling** [comment]
如果你之前有训练过，而且改变了数据集，那要删掉models这个文件夹，重新训练。

**Comment by 519994824** [comment]
> 如果你之前有训练过，而且改变了数据集，那要删掉models这个文件夹，重新训练。

哦哦，原来是这样，感谢
