### ISSUE TITLE
An error occurred when use pretrained model to train WenetSpeech dataset

### ISSUE THREAD

**Issue by tcexeexe** [yeyupiaoling/PPASR#30]
Hello~
     l copy the  pretrained model  form "PPASR_大数据集/models/deepspeech2/best_model" to the "/PPASR/models/deepspeech2/last_model", then l start  trainning, but an error occurred. l wonder what's the reason of this problem?

AssertionError: Variable Shape not match, Variable [ linear_0.w_0_moment1_0 ] need tensor with shape (1024, 5451) but load set tensor with shape (1024, 6436)
<img width="633" alt="微信图片_20220205190959" src="https://user-images.githubusercontent.com/28287196/152639709-7749632c-97d0-481b-9343-bb4b147ad332.png">

**Comment by yeyupiaoling** [comment]
Because dictionaries are different sizes.  It is recommended to use all the files in the pre-training dataset.

**Comment by tcexeexe** [comment]
> Because dictionaries are different sizes. It is recommended to use all the files in the pre-training dataset.

好的，谢谢!

**Comment by tcexeexe** [comment]
> Because dictionaries are different sizes. It is recommended to use all the files in the pre-training dataset.
你好，那如果按照你的意思，我要在原有模型上，添加新的词语，做迁移学习的话，是不是就不行了

**Comment by yeyupiaoling** [comment]
那个大数据的字典基本已经包括常用的汉字了

**Comment by tcexeexe** [comment]
> 那个大数据的字典基本已经包括常用的汉字了

好的
