### ISSUE TITLE
Android预计什么时候支持

### ISSUE THREAD

**Issue by wy676579037** [yeyupiaoling/PPASR#32]

**Comment by wy676579037** [comment]
做成Android版本的话，需要做哪些工作？我看下能不能基于你的自己实现下

**Comment by yeyupiaoling** [comment]
三步：
第一步：数据预处理，难度在Android上实现本项目的数据预处理
第二步：将模型导出为Paddle Lite模型
第三步：结果解码，一般用贪心解码
