### ISSUE TITLE
WenetSpeech训练时间的问题

### ISSUE THREAD

**Issue by tcexeexe** [yeyupiaoling/PPASR#33]
您好~
     按照项目的说明在训练WenetSpeech数据集，目前是单卡3090；但是看log提示，全部训练完65个epoch需要至少半年时间，同时看GPU的利用率也不是很高。我是初学者, 想请教下主要的瓶颈可能在哪里，有没有什么包括升级硬件在内的优化方法呢？
<img width="572" alt="ee88a540aad1e622f305ce669107a20" src="https://user-images.githubusercontent.com/28287196/153693559-a8ea7579-f5e8-4f96-8060-d12e0532eb9d.png">

**Comment by yeyupiaoling** [comment]
>GPU的利用率也不是很高

根据你这种情况，最重要的是使用固态硬盘存储音频数据，因为文件超级多，所以机械硬盘读取会很慢，导致GPU的利用率不高。
其次是CPU，因为音频预处理用CPU计算的，我看你数据读取线程数为32，估计你的CPU至少32核把，那CPU这个不是问题了。

**Comment by tcexeexe** [comment]
> > GPU的利用率也不是很高
> 
> 根据你这种情况，最重要的是使用固态硬盘存储音频数据，因为文件超级多，所以机械硬盘读取会很慢，导致GPU的利用率不高。 其次是CPU，因为音频预处理用CPU计算的，我看你数据读取线程数为32，估计你的CPU至少32核把，那CPU这个不是问题了。

好的，多谢指导！
