### ISSUE TITLE
训练是loss很不稳定,字错率下降慢

### ISSUE THREAD

**Issue by panliang5020** [yeyupiaoling/PPASR#35]
目前模型已经训练了14个epoch,训练时loss频繁变化,最低为1,最高可到40多,字错率从初始0.57下降到0.49,不知道这是否是正常现象
![image](https://user-images.githubusercontent.com/51695693/153999751-8db852ad-dbf4-434d-a4a2-79d13f7b659f.png)

**Comment by yeyupiaoling** [comment]
这应该是正常的，你训练那个数据集？

**Comment by panliang5020** [comment]
> 这应该是正常的，你训练那个数据集？

WenetSpeech数据集与前三个开源小型数据集

**Comment by yeyupiaoling** [comment]
字错率一开始就是0.57 ？batch size是多少？

**Comment by panliang5020** [comment]
> 字错率一开始就是0.57 ？batch size是多少？

![image](https://user-images.githubusercontent.com/51695693/154008708-8045e8eb-732b-4859-b2ef-f209d970975e.png)
batch size 32  使用多卡训练

**Comment by yeyupiaoling** [comment]
是正常的，一般是在20多轮的时候有较大的下降。你也可以用VisualDL查看训练log的变化，有loss有没有在减小的趋势。要看整体趋势，不能只看某个值，因为音频的长度不一。

**Comment by yeyupiaoling** [comment]
训练时间有点久，训练时，GPU占用大吗？

**Comment by panliang5020** [comment]
> 训练时间有点久，训练时，GPU占用大吗？

两块卡一共占了27g多,训练速度属实有点慢了,一个epoch37,8小时

**Comment by yeyupiaoling** [comment]
我问得是这个占用率。因为通常情况下，数据读取和预处理会导致GPU的占用率不够，WenetSpeech的数量很多，如果是机械硬盘，会导致读取速度变慢。

这个要注意。

![image](https://user-images.githubusercontent.com/26297768/154010198-0e6eccec-ce67-4d26-afc3-6857e04ef8aa.png)

**Comment by panliang5020** [comment]
![image](https://user-images.githubusercontent.com/51695693/154011003-67533c85-d13e-40e8-807f-4abd462910fc.png)

**Comment by yeyupiaoling** [comment]
这就没问题了。等训练20多轮的时候变化情况

**Comment by panliang5020** [comment]
> 这就没问题了。等训练20多轮的时候变化情况

好的,感谢解惑

**Comment by yeyupiaoling** [comment]
有变化吗？

**Comment by panliang5020** [comment]
> 有变化吗？
![image](https://user-images.githubusercontent.com/51695693/157161655-3ae148ce-d385-47e6-bcb7-e63df602de0a.png)

依旧表现不太好,字错率没有下降

**Comment by yeyupiaoling** [comment]
对了，现在提供了更大的模型`deepspeech2_big`，你可以试试这个模型训练。
https://github.com/yeyupiaoling/PPASR/blob/51419869a378fbd4a5db9f937d2e42d88d5fe89d/train.py#L15
