### ISSUE TITLE
求助一下，wenetspeech的训练配置

### ISSUE THREAD

**Issue by 519994824** [yeyupiaoling/PPASR#37]
麻烦大佬告知一下训练wenetspeech一万个小时数据集的时候，用几张什么显卡大概跑了多久呢，想预估一下自己这边的情况，万分感谢！

**Comment by yeyupiaoling** [comment]
我没跑完过，不清楚

**Comment by 519994824** [comment]
> 我没跑完过，不清楚

好吧，还是感谢🙏
