### ISSUE TITLE
运行train.py没有调用GPU训练

### ISSUE THREAD

**Issue by Shehold** [yeyupiaoling/PPASR#39]
作者你好，我train.py后训练数据调用的是cpu，没有调用到GPU，我用paddle.fluid.install_check.run_check()检查显示在GPU或CPU上运行良好。希望你能解答一下，谢谢！

**Comment by yeyupiaoling** [comment]
你说一直都是吗？因为一开始会加载数据，使用的是CPU，到正式训练才会使用到GPU。

**Comment by Shehold** [comment]
> 你说一直都是吗？因为一开始会加载数据，使用的是CPU，到正式训练才会使用到GPU。

加载batch的时候，每加载100大概需要20分钟，这个时候还没开始调用GPU吗？
[2022-02-20 22:32:00.946663] Train epoch: [1/65], batch: [0/835], loss: 829.43005, learning rate: 0.00005000, eta: 6 days, 19:10:14

**Comment by yeyupiaoling** [comment]
这时候应该调用了，你看GPU的显存有正常占用吗？

**Comment by Shehold** [comment]
> 这时候应该调用了，你看GPU的显存有正常占用吗？

没有，我的GPU1是显卡，它占用是0

**Comment by yeyupiaoling** [comment]
可能是环境的问题吧，你是不是GPU环境和CPU混合了。要不重新创建一个conda虚拟环境

**Comment by Shehold** [comment]
> 可能是环境的问题吧，你是不是GPU环境和CPU混合了。要不重新创建一个conda虚拟环境

好的谢谢，我试试

**Comment by yeyupiaoling** [comment]
@Shehold 怎么样？

**Comment by Shehold** [comment]
> @Shehold 怎么样？
我把项目部署在百度paddle平台上后成功了，应该是环境的问题。

**Comment by Shehold** [comment]
> @Shehold怎么样？

我把项目部署在百度paddle平台上后成功了，应该是环境的问题。
