### ISSUE TITLE
visualDL提示无“无可视化结果展示”

### ISSUE THREAD

**Issue by tcexeexe** [yeyupiaoling/PPASR#40]
你好~
       在训练WenetSpeech的过程中想查看训练日志，但是输入`visualdl --logdir=./log --host=0.0.0.0`或者`visualdl --logdir=log --host=0.0.0.0`后，在visualDL页面中都提示无可视化结果展示，目前除了修改了部分训练参数外，没有对clone下来的代码进行过修改。对paddlepaddle框架不大熟悉，想请教下，这可能是什么原因导致的？
<img width="856" alt="微信图片_20220220234529" src="https://user-images.githubusercontent.com/28287196/154851208-4cc926ed-5622-4179-b459-647b0b763e5f.png">
<img width="960" alt="微信图片_20220220234548" src="https://user-images.githubusercontent.com/28287196/154851210-4f36bd64-a6a0-450b-a77c-2dde5b8d1e19.png">
<img width="409" alt="微信图片_20220220234559" src="https://user-images.githubusercontent.com/28287196/154851211-65f1fb43-1332-4607-b427-654e1ccacad7.png">

**Comment by yeyupiaoling** [comment]
这个应该就是你最新训练的吧，看大小应该是还没有数据，你是训练不久吗？可能还没有数据写入。

![image](https://user-images.githubusercontent.com/26297768/154872364-09816124-8b52-4f4a-a7a1-7bf0185fe610.png)

**Comment by tcexeexe** [comment]
> 这个应该就是你最新训练的吧，看大小应该是还没有数据，你是训练不久吗？可能还没有数据写入。
> 
> ![image](https://user-images.githubusercontent.com/26297768/154872364-09816124-8b52-4f4a-a7a1-7bf0185fe610.png)

好的，谢谢！
