### ISSUE TITLE
语言模型相关

### ISSUE THREAD

**Issue by ftdzh1994** [yeyupiaoling/PPASR#42]
目前想在现有语言模型的基础上针对专有名词做一个增强，想法有两种：
一是直接修改语言模型中 n-gram的概率，但好像 klm 不支持修改；
二是在原有语料集的基础上增加语料并重新训练，但不知道语料集的出处（好像是百度内部语料集）。

所以在这请教一下，有什么好的实现路径吗？

**Comment by yeyupiaoling** [comment]
一、这应该是不支持的，如果支持添加热词了
二，原有的数据是百度内部的，没有原数据，重新训练不现实。

还是要了解热词解码的方式。
