### ISSUE TITLE
生成数据时遇到的问题

### ISSUE THREAD

**Issue by Mercury-x** [yeyupiaoling/PPASR#43]
您好，我在ai studio跑该项目的时候，在处理数据部分遇到了下面这个问题，请问是为什么？
_以及，在数据划分中，test.txt中每一条音频的路径有一些错误。被写入到test.txt中的路径是_aset/_开头的，而不是_dataset_开头的，您有空可以去修改一下。

---------------------------------------------------------------------------
IsADirectoryError                         Traceback (most recent call last)
/tmp/ipykernel_189/311691653.py in <module>
      7                        num_workers=1)
      8 
----> 9 trainer.create_data(annotation_path='dataset/annotation/')

~/PPASR/ppasr/trainer.py in create_data(self, annotation_path, noise_manifest_path, noise_path, num_samples, count_threshold, is_change_frame_rate, max_test_manifest)
    108                         test_manifest_path=self.test_manifest,
    109                         is_change_frame_rate=is_change_frame_rate,
--> 110                         max_test_manifest=max_test_manifest)
    111         print('=' * 70)
    112         print('开始生成噪声数据列表...')

~/PPASR/ppasr/utils/utils.py in create_manifest(annotation_path, train_manifest_path, test_manifest_path, is_change_frame_rate, max_test_manifest)
     53     for annotation_text in os.listdir(annotation_path):
     54         annotation_text_path = os.path.join(annotation_path, annotation_text)
---> 55         with open(annotation_text_path, 'r', encoding='utf-8') as f:
     56             lines = f.readlines()
     57         for line in tqdm(lines):

IsADirectoryError: [Errno 21] Is a directory: 'dataset/annotation/.ipynb_checkpoints'

**Comment by yeyupiaoling** [comment]
删除这个文件`'dataset/annotation/.ipynb_checkpoints`

这个是Jupyter自动生成的。

**Comment by Mercury-x** [comment]
> 删除这个文件`'dataset/annotation/.ipynb_checkpoints`
> 
> 这个是Jupyter自动生成的。

可以了！非常感谢！！

**Comment by Shehold** [comment]
> > 删除这个文件`'dataset/annotation/.ipynb_checkpoints`
> > 这个是Jupyter自动生成的。
> 
> 可以了！非常感谢！！

你好，我也遇到了你的这个问题，但是我在annotation里面没有找到.ipynb_checkpoints这个文件，请问你是如何解决的呢，我也是在ai studio上运行的，希望你能解答一下，谢谢！

**Comment by yeyupiaoling** [comment]
删除这个文件

**Comment by Shehold** [comment]
> 删除这个文件

我的annotation里面没有这个文件，但是报错却有这个问题。
![image](https://user-images.githubusercontent.com/97215854/159156290-ef61a958-5e32-4ac6-b451-801fa0f04138.png)
![image](https://user-images.githubusercontent.com/97215854/159156320-b643c693-d8c9-4b33-aac5-5ff68db8532d.png)

**Comment by yeyupiaoling** [comment]
这个应该是隐藏文件。

**Comment by Shehold** [comment]
> 这个应该是隐藏文件。


删除后可以运行了，谢谢作者您的耐心解答！！帮了我这个小白的大忙！
