### ISSUE TITLE
语音合成如何利用speaker_audio下自由音频

### ISSUE THREAD

**Issue by LiangDazhu** [yeyupiaoling/PPASR#44]
“把需要说话人的语音放在tools/generate_audio/speaker_audio目录下，可以使用dataset/test.wav文件，可以到找多个人的音频放在tools/generate_audio/speaker_audio目录下，开发者也可以尝试入自己的音频放入该目录，这样训练出来的模型能更好识别开发者的语音，采样率最好是16000Hz。”

大佬我没看到利用speaker_audio目录下音频信息的代码， 我看它合成的音频说话人都是取自下载的模型中models/fastspeech2_nosil_aishell3_ckpt_0.4/speaker_id_map.txt， 这个是后续会开发还是说我看错了，麻烦您解惑！

**Comment by yeyupiaoling** [comment]
这个已经更新了，不是原来的方式。你看最新的文档

**Comment by LiangDazhu** [comment]
您好， 我看了这个数据合成文件的历史提交记录， 只改动了模型下载的路径， 这是我看的文档路径：
https://github.com/yeyupiaoling/PPASR/blob/master/docs/generate_audio.md

您说的最新的文档是指哪个呢

**Comment by yeyupiaoling** [comment]
不好意思，是我没改文档。以前是根据语音文件克隆说话人的，现在是使用改为随机说话人的。

**Comment by LiangDazhu** [comment]
感谢解惑， 项目特别好， 感谢分享！
