### ISSUE TITLE
[2022-03-14 21:08:52.489487] 短语音识别失败，错误信息：unknown format: 6

### ISSUE THREAD

**Issue by tcxiaotudou** [yeyupiaoling/PPASR#45]
启动web服务后，上传录音一直报这个错误

**Comment by yeyupiaoling** [comment]
全部日志看下！

**Comment by dtMndas** [comment]
我也遇到同样的问题，mp3 先转 wav 格式，然后选择帧率16000，就会出现这个问题，然后把录音的帧率从16000 降低为8000，就可以了 ，我是用这个网站转换的 https://convertio.co/zh/audio-converter/

**Comment by yeyupiaoling** [comment]
本项目是支持读取mp3格式的，默认采样率是16k的
