### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by Zomun** [yeyupiaoling/PPASR#46]
I found that the accuracy maybe worser than before,how you guys think?

**Comment by yeyupiaoling** [comment]
你说的以前是指那个呢？

**Comment by Zomun** [comment]
PPASR相对于PaddlePaddleSpeech，不知道是否是我这边测试的问题

**Comment by Zomun** [comment]
vocabulary.txt这个文件生成的是词频统计，应该是对的吧

**Comment by yeyupiaoling** [comment]
是词汇表，同时也有统计功能。

**Comment by yeyupiaoling** [comment]
>PPASR相对于PaddlePaddleSpeech，不知道是否是我这边测试的问题
PaddlePaddleSpeech模型会大一些，也许是这个问题。或者是你使用的解码方法或者训练的数据集不一样
