### ISSUE TITLE
下载数据集后解压失败

### ISSUE THREAD

**Issue by bird7code** [yeyupiaoling/PPASR#49]
你好，我想问下将filepath指定为数据集的绝对路径，然后运训aishell.py报错误：EOFError: Compressed file ended before the end-of-stream marker was reached是什么问题？

**Comment by yeyupiaoling** [comment]
估计是你下载的文件不完整吧。

**Comment by bird7code** [comment]
> 

谢谢，已解决，从URL下载下来的数据集是有问题的，修复一下就可以了

**Comment by bird7code** [comment]
你好，下载的data_aishell.tgz中没有transcripts文件，是需要更换其他源下载吗还是什么问题

**Comment by bird7code** [comment]
> 你好，下载的data_aishell.tgz中没有transcripts文件，是需要更换其他源下载吗还是什么问题

已解决，更换一个源即可
