### ISSUE TITLE
test cer 总是1.0

### ISSUE THREAD

**Issue by feifaxiaoming** [yeyupiaoling/PPASR#5]
您好，麻烦问一下，我用的thchs30的训练集训练的，训练了50个epoch 但是test cer的值一直都是1.0，这个是为什么？
参数用的是默认的参数，没去做调整

![444](https://user-images.githubusercontent.com/27333423/128652457-2c5cea11-8d24-4e4a-a7f0-8398dc6d3c5c.png)

机器是
ubuntu16.04  
GPU tiant xp  
12G显存

**Comment by yeyupiaoling** [comment]
@feifaxiaoming 你用的进阶版吗？这个分支还在开发中，不过最新的代码训练部分基本可用了

**Comment by feifaxiaoming** [comment]
对，是用的进阶版的，是需要重新下载代码吗？您上周更新了？

**Comment by yeyupiaoling** [comment]
今天更新的

**Comment by feifaxiaoming** [comment]
好的，我在看看，谢谢

**Comment by feifaxiaoming** [comment]
您这代码已经传上来了吗

**Comment by yaoxunji** [comment]
入门版thchs30数据集训练完了loss在6.5左右，cer在0.97。这是咋回事

**Comment by yeyupiaoling** [comment]
@yaoxunji 不会吧，再次训练试试呢？

**Comment by yaoxunji** [comment]
> @yaoxunji 不会吧，再次训练试试呢？

我再试试用aishell训练

**Comment by Skeleton003** [comment]
> 入门版thchs30数据集训练完了loss在6.5左右，cer在0.97。这是咋回事

你好，请问你解决了吗，我用入门版训练，cer总是1.0
