### ISSUE TITLE
支持立体声吗?

### ISSUE THREAD

**Issue by lonelyxmas** [yeyupiaoling/PPASR#52]
请教一下:
1.支持立体声
2.有支持对话式的语音转文字(带时间戳)?

**Comment by yeyupiaoling** [comment]
1、立体声会自动转为单通道识别的。
2、你说的带时间戳是什么意思？

**Comment by lonelyxmas** [comment]
> 

感谢老大回复,
双声道,出来应该是一个两段不同的文字。
最终的效果：

**Comment by lonelyxmas** [comment]
【客服】【00:00:00】 你好

**Comment by yeyupiaoling** [comment]
这种需要你分割再输入得模型中

**Comment by lonelyxmas** [comment]
> 这种需要你分割再输入得模型中

感谢， 不过不是很理解，初学者，正在研究学习中。
