### ISSUE TITLE
实时录音正确率很低，怎么调整

### ISSUE THREAD

**Issue by eclwu** [yeyupiaoling/PPASR#53]
作者，您好，我想请教下
1. 运行infer_gui.py文件后，在显示的页面进行实时录音识别，识别率很低，单纯的词语都无法识别，请问该怎么调整
2. 我是直接下载模型，导出后进行预测的，试着运行了eval.py文件，提醒说没有mainfest.test这个文件，我又运行了create_data.py文件后还是没有生成mainfest.test这个文件

**Comment by yeyupiaoling** [comment]
1、你用的是哪个模型？因为数据集比较少，准确率是低了点
2、你下载数据了吗？需要下载数据生成数据列表才能评估模型的。

**Comment by eclwu** [comment]
> 1、你用的是哪个模型？因为数据集比较少，准确率是低了点 2、你下载数据了吗？需要下载数据生成数据列表才能评估模型的。

我下载的是thchs_30这个模型，但是我按他其中一条音频的语句说了一遍也还是识别不了

**Comment by eclwu** [comment]
> 1、你用的是哪个模型？因为数据集比较少，准确率是低了点 2、你下载数据了吗？需要下载数据生成数据列表才能评估模型的。

我下载的是thchs_30这个模型，但是我按他其中一条音频的语句说了一遍也还是识别不了

**Comment by eclwu** [comment]
> > 1、你用的是哪个模型？因为数据集比较少，准确率是低了点 2、你下载数据了吗？需要下载数据生成数据列表才能评估模型的。
> 
> 我下载的是thchs_30这个模型，但是我按他其中一条音频的语句说了一遍也还是识别不了

还想再请教下，如果使用集束搜索，识别率提高的多不多

**Comment by yeyupiaoling** [comment]
thchs_30这数据集比较小，你换个大一点的数据模型
高很多

**Comment by eclwu** [comment]
> thchs_30这数据集比较小，你换个大一点的数据模型 高很多

我刚刚试了一下aishell这个模型，导出模型后运行infer_gui.py报了一个错：ValueError: operands could not be broadcast together with shapes (161,838) (39,1)，想再麻烦您解答一下，我在百度上没有找到相关解决方法

**Comment by yeyupiaoling** [comment]
dataset有个文件你没替换。

**Comment by eclwu** [comment]
> dataset有个文件你没替换。

我替换了zh_vocab.txt和mean_std.npz这两个文件，还需要替换哪些文件

**Comment by yeyupiaoling** [comment]
你下载错模型了，

**Comment by yeyupiaoling** [comment]
你要在项目的主页下载

**Comment by eclwu** [comment]
> 你要在项目的主页下载

我现在运行的是你之前静态图实现那个版本的，现在这个最终版本的模型还在下载中

**Comment by eclwu** [comment]
> > 你要在项目的主页下载
> 
> 我现在运行的是你之前静态图实现那个版本的，现在这个最终版本的模型还在下载中

我重新下载看看
