### ISSUE TITLE
预测模型出错

### ISSUE THREAD

**Issue by eclwu** [yeyupiaoling/PPASR#54]
作者，您好，我下载了aishell这个模型，导出模型后，打开gui页面，选择一个文件进行识别时，出现了这种情况：
已选择音频文件：C:/Users/15468/Desktop/最终版/PPASR/dataset/test.wav
正在识别中...
消耗时间：1968ms, 识别结果: 莲朵姻朵蹈帅址帅滩汪姻睿涛遵泸功帅歌帅遵俱逾帅到滩姻址帅碗帅涛滩碗滩俱碗帅急址疯砥陪卤碗遵泸碗菌僻帅淆滩姻朵, 得分: 0

想请教下是什么原因

**Comment by yeyupiaoling** [comment]
这个不用导出模型，下载的文件里面包含了预测模型的

**Comment by yeyupiaoling** [comment]
这个不用导出模型，下载的文件里面包含了预测模型的

**Comment by zzq1261310130** [comment]
你好，这个乱七八糟的结果的问题解决了吗
