### ISSUE TITLE
请问有效果较好的模型吗

### ISSUE THREAD

**Issue by mrright2019** [yeyupiaoling/PPASR#55]
我用了大规模的那个模型识别了下央视的直播的声音，效果并不如预期。
![image](https://user-images.githubusercontent.com/30712720/164192835-b85fdf36-12a5-48bf-9481-920580a2fe6c.png)

**Comment by yeyupiaoling** [comment]
你试试使用集束搜索解码，看效果会不会好一些
那个数据大部分都是安静的录音场景，wenetspeech数据就是电视的声音，用这个训练应该会好很多

**Comment by mrright2019** [comment]
> 我测试的音频也是安静的场景，是ffmpeg直播转录得到的wav文件

**Comment by yeyupiaoling** [comment]
用什么解码方法？

**Comment by mrright2019** [comment]
> 用什么解码方法？

ctc_greedy

**Comment by yeyupiaoling** [comment]
用：ctc_beam_search 试试
