### ISSUE TITLE
conformer_wenetspeech预训练模型基础上，调整部分关键词权重

### ISSUE THREAD

**Issue by 907122187** [yeyupiaoling/PPASR#57]
想请教一下，使用[PaddleSpeech](https://github.com/PaddlePaddle/PaddleSpeech)的时候，默认使用了conformer_wenetspeech预训练模型，大多数情况下识别较好，但对于我们场景的部分关键词，可能要在预训练的基础上调整权重，这个要怎么实现？

**Comment by yeyupiaoling** [comment]
PaddleSpeech我用得不多，不知道有没有热词解码。如果有可以添加这些热词，解码的时候，这个关键词会得分高一些。如果没有，可能要重新训练，把你的数据和wenetspeech混合训练。

**Comment by 907122187** [comment]
好，谢谢博主，在[PaddleSpeech](https://github.com/PaddlePaddle/PaddleSpeech)看到的是目前还不知支持

https://github.com/PaddlePaddle/PaddleSpeech/issues/716
