### ISSUE TITLE
结果乱码

### ISSUE THREAD

**Issue by chengming1108** [yeyupiaoling/PPASR#59]
alpha: 2.2
beam_size: 300
beta: 4.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoder: ctc_greedy
feature_method: linear
is_long_audio: False
lang_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
model_dir: models/deepspeech2/infer/
pun_model_dir: models/pun_models/
real_time_demo: False
to_an: False
use_gpu: True
use_model: deepspeech2
use_pun: False
vocab_path: dataset/vocabulary.txt
wav_path: ./dataset/test.wav
------------------------------------------------
E0506 16:49:20.850978 19184 analysis_config.cc:91] Please compile with gpu to EnableGpu()
消耗时间：1067ms, 识别结果: 炊拴炊锻岭锻炊势拴岭姨锻炊旧锻性野纯舰锻炊参锻顶锻拴探锻性拴锻射野驰蜕锻顶射拴炊势拴引地练顶锻参岭锻普顶锻卧炊, 得分: 0

**Comment by zzq1261310130** [comment]
你好，你解决了这个问题吗，我也遇到类似问题

**Comment by zhangzuoxing** [comment]
> ## alpha: 2.2
> beam_size: 300
> beta: 4.3
> cutoff_prob: 0.99
> cutoff_top_n: 40
> decoder: ctc_greedy
> feature_method: linear
> is_long_audio: False
> lang_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
> model_dir: models/deepspeech2/infer/
> pun_model_dir: models/pun_models/
> real_time_demo: False
> to_an: False
> use_gpu: True
> use_model: deepspeech2
> use_pun: False
> vocab_path: dataset/vocabulary.txt
> wav_path: ./dataset/test.wav
> E0506 16:49:20.850978 19184 analysis_config.cc:91] Please compile with gpu to EnableGpu() 消耗时间：1067ms, 识别结果: 炊拴炊锻岭锻炊势拴岭姨锻炊旧锻性野纯舰锻炊参锻顶锻拴探锻性拴锻射野驰蜕锻顶射拴炊势拴引地练顶锻参岭锻普顶锻卧炊, 得分: 0



> 你好，你解决了这个问题吗，我也遇到类似问题

同遇到这个问题，用大规模数据集的模型，用export_model重新导出一下，预测结果乱码。如果不重新导出，原位替代，代码报错

**Comment by zhangzuoxing** [comment]
同遇到这个问题，用大规模数据集的模型，用export_model重新导出一下，预测结果乱码。如果不重新导出，原位替代，代码报错。不知道怎么解决

**Comment by zzq1261310130** [comment]
有可能是输入模型的分类概率矩阵出错了，我的就是这个原因，不过我用的不是这个模型，只是类似

**Comment by chengming1108** [comment]
下载下来的模型有问题，可能乱码了，我自己训练了5轮 生成了三个文件 导出模型后可以用，并没有乱码，就是得分比较低。一开始以为是解码器的问题，现在看来就是模型文件的问题喽 。可以自己训练一下 5轮 loss100多 。50轮应该差不多，自己训练一个可以用。模型我用tb买的下载链接下的。可能会出问题；可以加v交流一下 CM995958609

**Comment by chengming1108** [comment]
> 有可能是输入解码器的分类概率矩阵出错了，我的就是这个原因，不过我用的不是这个模型，只是类似

CSND 下载 不要用其他的下载器下载 否则会缺少文件

**Comment by chengming1108** [comment]
> 同遇到这个问题，用大规模数据集的模型，用export_model重新导出一下，预测结果乱码。如果不重新导出，原位替代，代码报错。不知道怎么解决

去CSND下载。用别的下载可能会缺文件

**Comment by yeyupiaoling** [comment]
不需要重新导出模型的，下载文件之后，解压，把全部文件复制到项目根目录中，替换原来的文件。

**Comment by chengming1108** [comment]
问题解决
