### ISSUE TITLE
aishell cer

### ISSUE THREAD

**Issue by yingzhao27** [yeyupiaoling/PPASR#60]
您好，请问您在README中展示的用AISHELL数据集训练的模型test-CER=0.077042是在什么配置下训练获得的呢，是按照您代码提供的配置吗，
我训练出来测试时词错率为0.11767，感觉还差挺多呢

**Comment by zzq1261310130** [comment]
我也没有达到这个cer，是不是只测了少部分数据，没有测试全部测试集

**Comment by zzq1261310130** [comment]
> 您好，请问您在README中展示的用AISHELL数据集训练的模型test-CER=0.077042是在什么配置下训练获得的呢，是按照您代码提供的配置吗， 我训练出来测试时词错率为0.11767，感觉还差挺多呢


解码时，你给的α和β分别多少

**Comment by yingzhao27** [comment]
> 

我按照作者提供的训练的，没改过

**Comment by zzq1261310130** [comment]
> > 
> 
> 我按照作者提供的训练的，没改过

你训练了多少epoch，最后loss多少

**Comment by yingzhao27** [comment]
>



> > > 
> > 
> > 
> > 我按照作者提供的训练的，没改过
> 
> 你训练了多少epoch，最后loss多少

65epoch,loss 16.29016,cer: 0.29169

**Comment by zzq1261310130** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > 我按照作者提供的训练的，没改过
> > 
> > 
> > 你训练了多少epoch，最后loss多少
> 
> 65epoch,loss 16.29016,cer: 0.29169

loss这么大？会欠拟合吧？

**Comment by yingzhao27** [comment]
> > > 
> > 
> > 
> > > > > 
> > > > 
> > > > 
> > > > 我按照作者提供的训练的，没改过
> > > 
> > > 
> > > 你训练了多少epoch，最后loss多少
> > 
> > 
> > 65epoch,loss 16.29016,cer: 0.29169
> 
> loss这么大？会欠拟合吧？

我觉得我训练有点问题，loss一直在震荡，最小在2.5左右

**Comment by zzq1261310130** [comment]
> > > > 
> > > 
> > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我按照作者提供的训练的，没改过
> > > > 
> > > > 
> > > > 你训练了多少epoch，最后loss多少
> > > 
> > > 
> > > 65epoch,loss 16.29016,cer: 0.29169
> > 
> > 
> > loss这么大？会欠拟合吧？
> 
> 我觉得我训练有点问题，loss一直在震荡，最小在2.5左右

可能学习率大了

**Comment by yingzhao27** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 我按照作者提供的训练的，没改过
> > > > > 
> > > > > 
> > > > > 你训练了多少epoch，最后loss多少
> > > > 
> > > > 
> > > > 65epoch,loss 16.29016,cer: 0.29169
> > > 
> > > 
> > > loss这么大？会欠拟合吧？
> > 
> > 
> > 我觉得我训练有点问题，loss一直在震荡，最小在2.5左右
> 
> 可能学习率大了

请问你用的多大的学习率、epoch和batchsize是多少啊

**Comment by zzq1261310130** [comment]
数据集aishell-1，0.00005、80、64

**Comment by zzq1261310130** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 我按照作者提供的训练的，没改过
> > > > > > 
> > > > > > 
> > > > > > 你训练了多少epoch，最后loss多少
> > > > > 
> > > > > 
> > > > > 65epoch,loss 16.29016,cer: 0.29169
> > > > 
> > > > 
> > > > loss这么大？会欠拟合吧？
> > > 
> > > 
> > > 我觉得我训练有点问题，loss一直在震荡，最小在2.5左右
> > 
> > 
> > 可能学习率大了
> 
> 请问你用的多大的学习率、epoch和batchsize是多少啊

数据集aishell-1，0.00005、80、64

**Comment by yeyupiaoling** [comment]
是你在评估的时候没有选择集束搜索解码策略

**Comment by yingzhao27** [comment]
> 是你在评估的时候没有选择集束搜索解码策略

使用了集束搜索解码策略的。后面发现是因为batchsize，我用的8卡，batchsize=32的话训练效果不好。用1卡能复现0.075的错误率了

**Comment by yeyupiaoling** [comment]
应该是学习率的问题。
