### ISSUE TITLE
模型预测问题

### ISSUE THREAD

**Issue by LongWen66** [yeyupiaoling/PPASR#67]
预测时报错，如下
(PreconditionNotMet) The variable named audio_data is not found in the scope of the exector.
  [Hint: executor_->scope()->FindVar(name) should not be null.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:829)

**Comment by yeyupiaoling** [comment]
这个是缺失了audio_data参数，你有改动什么吗？
