### ISSUE TITLE
用自己的数据集出现问题。

### ISSUE THREAD

**Issue by PANPANKK** [yeyupiaoling/PPASR#68]
RuntimeError: Error opening 'dataset/audio/wav/0715/G1.wav  神鹿五两三四郑州雷达看到\n': System error.

想问下试了多个项目均不能读取音频和标签，是什么情况嘞？我的txt格式，音频路径格式均是按照要求来的。

**Comment by yeyupiaoling** [comment]
这个错误提示一般是路径不正确，你看看相对路径是否正确，或者看看音频文件有没有问题，你可以自己读取看看

**Comment by PANPANKK** [comment]
您好，我试过很多方法，比如 空格 tab ，也试过把绝对路径改为相对路径。在把路径改为相对后好像是能读取了，但是会出现list out of range的错误，还是读不了文件。想问下您有没有好的解决方案~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夜雨飘零 ***@***.***&gt;
发送时间: 2022年5月27日 08:36
收件人: yeyupiaoling/PPASR ***@***.***&gt;
抄送: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yeyupiaoling/PPASR] 用自己的数据集出现问题。 (Issue #68)

**Comment by yeyupiaoling** [comment]
看这个文档：https://github.com/yeyupiaoling/PPASR/blob/master/docs/dataset.md
用`\t`隔开的。

**Comment by PANPANKK** [comment]
有一个问题就是，是在txt文档里 音频位置和 标签中间用\t来隔开，但是在生成数据列表那个代码里，这一步line.split（'\t'）并没有去执行 分割。我想问作者您一个问题，就是我在文本里是用 tab隔开还是用\t隔开呢，我看您说是用\t ，但是这个图片中分割的 \t并没有显示，我用tab和\t有什么区别吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夜雨飘零 ***@***.***&gt;
发送时间: 2022年5月27日 08:46
收件人: yeyupiaoling/PPASR ***@***.***&gt;
抄送: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yeyupiaoling/PPASR] 用自己的数据集出现问题。 (Issue #68)

**Comment by yeyupiaoling** [comment]
如果你用手动的tab，pycharm会认为是4个空格、

**Comment by PANPANKK** [comment]
感觉不应该吧，我看我那个tab是根据位置来占位的呀。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夜雨飘零 ***@***.***&gt;
发送时间: 2022年5月27日 08:56
收件人: yeyupiaoling/PPASR ***@***.***&gt;
抄送: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yeyupiaoling/PPASR] 用自己的数据集出现问题。 (Issue #68)





 
如果你用手动的tab，pycharm会认为是4个空格、

**Comment by yeyupiaoling** [comment]
那你自己写一个简单的程序读取你的列表文件，看能不能读取到咯。参考这个：
https://github.com/yeyupiaoling/PPASR/blob/81d22aa6f814949f6d2803d59a42a3ac143cf7e3/ppasr/utils/utils.py#L55-L63
