### ISSUE TITLE
No such file or directory: 'dataset/vocabulary.txt'

### ISSUE THREAD

**Issue by billqu01** [yeyupiaoling/PPASR#69]
我把项目下载了。
执行 python infer_path.py --wav_path=./dataset/test.wav
报错：
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/vocabulary.txt'
项目里面也搜索不到vocabulary.txt
请问怎么解决？

**Comment by yeyupiaoling** [comment]
你下载资源文件解压复制到项目中了吗？

**Comment by billqu01** [comment]
我把这个项目都下载了。
请问那个文件是资源文件？

**Comment by billqu01** [comment]
我是从github，把PPASR-master.zip下载了，在本机解压的。
请问您说的资源文件叫什么名字？在PPASR-master文件夹中吗？
请指教。
非常感谢。

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/PPASR#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD

**Comment by yeyupiaoling** [comment]
看文档
