### ISSUE TITLE
自定义训练集是否需要切割并分别给出对应文字

### ISSUE THREAD

**Issue by a00147600** [yeyupiaoling/PPASR#70]
打算自定义训练集训练 但是手里的语音长度都在1分钟以上 是否需要切割出对应说话的片段来配合文字训练

**Comment by yeyupiaoling** [comment]
要切割的，我目前的都是固定20秒的。太长没有足够的显存训练。
https://github.com/yeyupiaoling/PPASR/blob/81d22aa6f814949f6d2803d59a42a3ac143cf7e3/train.py#L14
