### ISSUE TITLE
vocabulary.txt 如何得到？

### ISSUE THREAD

**Issue by billqu01** [yeyupiaoling/PPASR#71]
我是从github，把PPASR-master.zip下载了，在本机解压的。
请问从哪个文件解压得到vocabulary.txt ？
在PPASR-master文件夹中吗？
请指教。
非常感谢。

**Comment by yeyupiaoling** [comment]
你是训练还是预测，预测需要下载模型文件，看文档
‘https://github.com/yeyupiaoling/PPASR#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD’

**Comment by billqu01** [comment]
非常感谢。
请问是执行导出模型吗？
是看这一页吗？
https://github.com/yeyupiaoling/PPASR/blob/a3d4604b7e6b8923222f0f35e71cacc9534c313b/docs/export_model.md
我执行了。
python export_model.py --resume_model=models/deepspeech2/epoch_50/
但是报错：
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/vocabulary.txt'

**Comment by yeyupiaoling** [comment]
如果使用下载的模型，是包含了预测模型，不需要导出。

下载的文件要原本复制到项目中。
