### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.inference'

### ISSUE THREAD

**Issue by ydh11654686** [yeyupiaoling/PPASR#76]
运行的时候有下这个错误：
pip list|grep paddle
paddle                   1.0.2
paddlespeech-ctcdecoders 0.1.1
paddlespeech-feat        0.1.0

**Comment by yeyupiaoling** [comment]
安装最新的版本看看，
```
conda install paddlepaddle-gpu==2.3.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```

**Comment by ydh11654686** [comment]
@yeyupiaoling thanks. 电脑没有GPU可以吗

**Comment by yeyupiaoling** [comment]
推理可以使用CPU
安装CPU版本：
```
conda install paddlepaddle==2.3.0 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```

**Comment by ydh11654686** [comment]
@yeyupiaoling 谢谢，这个对c++的库有要求吗

ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lib/python3.7/site-packages/paddle/fluid/core_avx.so)

**Comment by ydh11654686** [comment]
@yeyupiaoling 谢谢, 刚遇到了另一个问题
# python infer_path.py --wav_path=/root/test.mp3 --use_gpu=False --is_long_audio=True --decoder=ctc_beam_search
Traceback (most recent call last):
  File "infer_path.py", line 6, in <module>
    from ppasr.predict import Predictor
  File "/root/PPASR-master/ppasr/predict.py", line 8, in <module>
    from ppasr.data_utils.audio import AudioSegment
  File "/root/PPASR-master/ppasr/data_utils/audio.py", line 5, in <module>
    import librosa
  File "python/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "python/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/python/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "python/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/python/lib/python3.7/site-packages/librosa/util/__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/python/lib/python3.7/site-packages/librosa/util/files.py", line 11, in <module>
    import pooch
  File "python/lib/python3.7/site-packages/pooch/__init__.py", line 19, in <module>
    from .processors import Unzip, Untar, Decompress
  File "python/lib/python3.7/site-packages/pooch/processors.py", line 14, in <module>
    import lzma
  File "/python/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Comment by ydh11654686** [comment]
@yeyupiaoling Linux上的[集束搜索解码是运行这个command吗，看介绍模型是自动下载，但是报了一个模型找不到的错误

python infer_path.py --wav_path=/root/test.mp3 --use_gpu=False --is_long_audio=True --decoder=ctc_beam_search


  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
-----------  Configuration Arguments -----------
alpha: 2.2
beam_size: 300
beta: 4.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoder: ctc_beam_search
feature_method: linear
is_long_audio: 1
lang_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
model_dir: models/deepspeech2/infer/
pun_model_dir: models/pun_models/
real_time_demo: False
to_an: False
use_gpu: 0
use_model: deepspeech2
use_pun: False
vocab_path: dataset/vocabulary.txt
wav_path: /root/test.mp3
------------------------------------------------
======================================================================
初始化解码器...
language model: is_character_based = 1, max_order = 5, dict_size = 0
初始化解码器完成!
======================================================================
Traceback (most recent call last):
  File "infer_path.py", line 39, in <module>
    feature_method=args.feature_method)
  File "/root/PPASR-master/ppasr/predict.py", line 82, in __init__
    raise Exception("模型文件不存在，请检查%s和%s是否存在！" % (model_path, params_path))
Exception: 模型文件不存在，请检查models/deepspeech2/infer/model.pdmodel和models/deepspeech2/infer/model.pdiparams是否存在！

**Comment by yeyupiaoling** [comment]
语言模型是可以自动下载，但是这个预测模型要自己下载。

**Comment by ydh11654686** [comment]
@yeyupiaoling 有下载link吗

**Comment by yeyupiaoling** [comment]
看项目主页文档

**Comment by ydh11654686** [comment]
@yeyupiaoling 模型下载了，但是推理出的结果还是很不准，不知道是什么原因？
python infer_path.py --wav_path=/root/test.mp3 --use_gpu=False --is_long_audio=True --decoder=ctc_beam_search
![图片](https://user-images.githubusercontent.com/59287976/173090682-f2ee6a26-d7c4-4f78-8c3e-656c1e830c77.png)

![图片](https://user-images.githubusercontent.com/59287976/173090507-ee526542-a92f-4436-b323-40f533ab50c3.png)

**Comment by yeyupiaoling** [comment]
用更大的数据集训练的模型。或者自己训练同一个分布的数据
