### ISSUE TITLE
“快速使用”文档中win不能下载文件

### ISSUE THREAD

**Issue by LIZ-CRYSTAL** [yeyupiaoling/PPASR#88]
按教程，“获取程序中的DATA_URL的下载地址单独下载”，显示“You don't have permission to access this resource.”
另，我按readme->模型下载，下载了thchs_30，里面是两个文件夹，直接解压到根目录么？

**Comment by yeyupiaoling** [comment]
模型是下载解压到根目录替换掉原来的。

**Comment by yeyupiaoling** [comment]
你单独下载数据，只要把链接拼接完整啊。

**Comment by LIZ-CRYSTAL** [comment]
'https://openslr.magicdatatech.com/resources/18/data_thchs30.tgz'但是这个链接并不能打开
另，我现在可以用wav文件进行识别了，请问流式语音输入要怎么实现呢？

**Comment by yeyupiaoling** [comment]
看了一下，好像下线了。

**Comment by yeyupiaoling** [comment]
@LIZ-CRYSTAL 又可以下载了
