### ISSUE TITLE
mean_std.npz这个不用吗,没有配置参数

### ISSUE THREAD

**Issue by wangcc57** [yeyupiaoling/PPASR#90]
mean_std.npz这个不用吗,没有配置参数

**Comment by yeyupiaoling** [comment]
内嵌到模型里面了。

**Comment by wangcc57** [comment]
> 内嵌到模型里面了。

具体代码在哪个位置,源码看了一遍,没有找到.

**Comment by yeyupiaoling** [comment]
在导出模型的时候放在模型中了，
https://github.com/yeyupiaoling/PPASR/blob/5920316281e5ba194e2ceb822c49f5eb7d3af253/ppasr/trainer.py#L501
