### ISSUE TITLE
现在可以做流式识别吗？

### ISSUE THREAD

**Issue by LIZ-CRYSTAL** [yeyupiaoling/PPASR#91]
如题。好像没有看到流式识别的文档。长语音还是要一整个音频输进去才能输出结果。

**Comment by yeyupiaoling** [comment]
完整的例子没有，只有这个简单的例子
https://github.com/yeyupiaoling/PPASR/blob/5920316281e5ba194e2ceb822c49f5eb7d3af253/infer_path.py#L65-L87

**Comment by yeyupiaoling** [comment]
这是模拟音频一个一个片段输入到模型中。这这是一个模拟例子

**Comment by yeyupiaoling** [comment]
现在GUI那个预测程序就是录音实时返回识别结果了。
