### ISSUE TITLE
wenet数据集，big模型不支持多卡训练吗？

### ISSUE THREAD

**Issue by qinwangmm** [yeyupiaoling/PPASR#94]
您好，请教一下。我用的wenet数据集，
设置单卡 export CUDA_VISIBLE_DEVICES=2
或单卡 export CUDA_VISIBLE_DEVICES=3
或者双卡 export CUDA_VISIBLE_DEVICES=2,3。其他训练参数都一样，只是占用了一个GPU 来训练模型，这个为什么呢？进阶版的代码我设置多卡，是支持多卡训练的。

**Comment by yeyupiaoling** [comment]
看文档说明：
https://github.com/yeyupiaoling/PPASR/blob/master/docs/train.md

**Comment by qinwangmm** [comment]
> 看文档说明： https://github.com/yeyupiaoling/PPASR/blob/master/docs/train.md

好了，谢谢，我原以为跟之前设置一样就可以呢
