### ISSUE TITLE
使用wenetspeech数据集训练，在多卡情况下，是不是需要调整训练参数呢（相对于单卡的情况）？

### ISSUE THREAD

**Issue by real-CLiang** [yeyupiaoling/PPASR#96]
您好！
我准备在三张3090上使用wenetspeech数据集来进行训练，请问在三张卡的情况下，训练时的参数应该按照您代码中的参数要进行倍数的调整吗？比如说batch_size，learning——rate等参数，另外我感觉训练轮次在这么大数据集的情况下 65轮会不会多了些呢？

**Comment by yeyupiaoling** [comment]
你用的是big模型吧，第1个epoch音频是从短到长的，你设置batch size的时候，要注意这点，不要出现显存溢出。
学习率的话可以增大三倍。
训练二三十轮应该可以的吧，不过具体还是要看，模型的拟合情况。
